import SwiftUI

/// Themed color tokens from Lemonade DS - Foundations
///
/// A generic, theme-aware hue palette sitting between the primitive ramps and the
/// semantic tokens in `LemonadeSemanticColors`. Use these when a colour carries
/// application meaning the design system does not model - chart series, categories,
/// per-role or per-status accents.
///
/// Prefer a semantic token whenever one fits.
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-themed-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-themed-token-converter.main.kts
///  
///  @generated by scripts/swiftui-themed-token-converter.main.kts
/// 

/// Themed amber color definitions
public protocol ThemedAmberColors {
    var background: Color { get }
    var backgroundSubtle: Color { get }
    var border: Color { get }
    var borderSubtle: Color { get }
    var content: Color { get }
    var contentOnColor: Color { get }
    var onBackground: Color { get }
}

/// Themed blue color definitions
public protocol ThemedBlueColors {
    var background: Color { get }
    var backgroundSubtle: Color { get }
    var border: Color { get }
    var borderSubtle: Color { get }
    var content: Color { get }
    var contentOnColor: Color { get }
    var onBackground: Color { get }
}

/// Themed cyan color definitions
public protocol ThemedCyanColors {
    var background: Color { get }
    var backgroundSubtle: Color { get }
    var border: Color { get }
    var borderSubtle: Color { get }
    var content: Color { get }
    var contentOnColor: Color { get }
    var onBackground: Color { get }
}

/// Themed fuchsia color definitions
public protocol ThemedFuchsiaColors {
    var background: Color { get }
    var backgroundSubtle: Color { get }
    var border: Color { get }
    var borderSubtle: Color { get }
    var content: Color { get }
    var contentOnColor: Color { get }
    var onBackground: Color { get }
}

/// Themed green color definitions
public protocol ThemedGreenColors {
    var background: Color { get }
    var backgroundSubtle: Color { get }
    var border: Color { get }
    var borderSubtle: Color { get }
    var content: Color { get }
    var contentOnColor: Color { get }
    var onBackground: Color { get }
}

/// Themed greenlime color definitions
public protocol ThemedGreenLimeColors {
    var background: Color { get }
    var backgroundSubtle: Color { get }
    var border: Color { get }
    var borderSubtle: Color { get }
    var content: Color { get }
    var contentOnColor: Color { get }
    var onBackground: Color { get }
}

/// Themed indigo color definitions
public protocol ThemedIndigoColors {
    var background: Color { get }
    var backgroundSubtle: Color { get }
    var border: Color { get }
    var borderSubtle: Color { get }
    var content: Color { get }
    var contentOnColor: Color { get }
    var onBackground: Color { get }
}

/// Themed orange color definitions
public protocol ThemedOrangeColors {
    var background: Color { get }
    var backgroundSubtle: Color { get }
    var border: Color { get }
    var borderSubtle: Color { get }
    var content: Color { get }
    var contentOnColor: Color { get }
    var onBackground: Color { get }
}

/// Themed pink color definitions
public protocol ThemedPinkColors {
    var background: Color { get }
    var backgroundSubtle: Color { get }
    var border: Color { get }
    var borderSubtle: Color { get }
    var content: Color { get }
    var contentOnColor: Color { get }
    var onBackground: Color { get }
}

/// Themed purple color definitions
public protocol ThemedPurpleColors {
    var background: Color { get }
    var backgroundSubtle: Color { get }
    var border: Color { get }
    var borderSubtle: Color { get }
    var content: Color { get }
    var contentOnColor: Color { get }
    var onBackground: Color { get }
}

/// Themed red color definitions
public protocol ThemedRedColors {
    var background: Color { get }
    var backgroundSubtle: Color { get }
    var border: Color { get }
    var borderSubtle: Color { get }
    var content: Color { get }
    var contentOnColor: Color { get }
    var onBackground: Color { get }
}

/// Themed rose color definitions
public protocol ThemedRoseColors {
    var background: Color { get }
    var backgroundSubtle: Color { get }
    var border: Color { get }
    var borderSubtle: Color { get }
    var content: Color { get }
    var contentOnColor: Color { get }
    var onBackground: Color { get }
}

/// Themed teal color definitions
public protocol ThemedTealColors {
    var background: Color { get }
    var backgroundSubtle: Color { get }
    var border: Color { get }
    var borderSubtle: Color { get }
    var content: Color { get }
    var contentOnColor: Color { get }
    var onBackground: Color { get }
}

/// Themed violet color definitions
public protocol ThemedVioletColors {
    var background: Color { get }
    var backgroundSubtle: Color { get }
    var border: Color { get }
    var borderSubtle: Color { get }
    var content: Color { get }
    var contentOnColor: Color { get }
    var onBackground: Color { get }
}

/// Themed yellow color definitions
public protocol ThemedYellowColors {
    var background: Color { get }
    var backgroundSubtle: Color { get }
    var border: Color { get }
    var borderSubtle: Color { get }
    var content: Color { get }
    var contentOnColor: Color { get }
    var onBackground: Color { get }
}

/// Themed yellowlime color definitions
public protocol ThemedYellowLimeColors {
    var background: Color { get }
    var backgroundSubtle: Color { get }
    var border: Color { get }
    var borderSubtle: Color { get }
    var content: Color { get }
    var contentOnColor: Color { get }
    var onBackground: Color { get }
}

/// Protocol defining themed color categories
public protocol LemonadeThemedColors {
    var amber: ThemedAmberColors { get }
    var blue: ThemedBlueColors { get }
    var cyan: ThemedCyanColors { get }
    var fuchsia: ThemedFuchsiaColors { get }
    var green: ThemedGreenColors { get }
    var greenLime: ThemedGreenLimeColors { get }
    var indigo: ThemedIndigoColors { get }
    var orange: ThemedOrangeColors { get }
    var pink: ThemedPinkColors { get }
    var purple: ThemedPurpleColors { get }
    var red: ThemedRedColors { get }
    var rose: ThemedRoseColors { get }
    var teal: ThemedTealColors { get }
    var violet: ThemedVioletColors { get }
    var yellow: ThemedYellowColors { get }
    var yellowLime: ThemedYellowLimeColors { get }
}

private struct AdaptiveThemedAmberColors: ThemedAmberColors {
    let background = Color("lemonade-themed-amber-background", bundle: .lemonade)
    let backgroundSubtle = Color("lemonade-themed-amber-background-subtle", bundle: .lemonade)
    let border = Color("lemonade-themed-amber-border", bundle: .lemonade)
    let borderSubtle = Color("lemonade-themed-amber-border-subtle", bundle: .lemonade)
    let content = Color("lemonade-themed-amber-content", bundle: .lemonade)
    let contentOnColor = Color("lemonade-themed-amber-content-on-color", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-amber-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedBlueColors: ThemedBlueColors {
    let background = Color("lemonade-themed-blue-background", bundle: .lemonade)
    let backgroundSubtle = Color("lemonade-themed-blue-background-subtle", bundle: .lemonade)
    let border = Color("lemonade-themed-blue-border", bundle: .lemonade)
    let borderSubtle = Color("lemonade-themed-blue-border-subtle", bundle: .lemonade)
    let content = Color("lemonade-themed-blue-content", bundle: .lemonade)
    let contentOnColor = Color("lemonade-themed-blue-content-on-color", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-blue-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedCyanColors: ThemedCyanColors {
    let background = Color("lemonade-themed-cyan-background", bundle: .lemonade)
    let backgroundSubtle = Color("lemonade-themed-cyan-background-subtle", bundle: .lemonade)
    let border = Color("lemonade-themed-cyan-border", bundle: .lemonade)
    let borderSubtle = Color("lemonade-themed-cyan-border-subtle", bundle: .lemonade)
    let content = Color("lemonade-themed-cyan-content", bundle: .lemonade)
    let contentOnColor = Color("lemonade-themed-cyan-content-on-color", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-cyan-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedFuchsiaColors: ThemedFuchsiaColors {
    let background = Color("lemonade-themed-fuchsia-background", bundle: .lemonade)
    let backgroundSubtle = Color("lemonade-themed-fuchsia-background-subtle", bundle: .lemonade)
    let border = Color("lemonade-themed-fuchsia-border", bundle: .lemonade)
    let borderSubtle = Color("lemonade-themed-fuchsia-border-subtle", bundle: .lemonade)
    let content = Color("lemonade-themed-fuchsia-content", bundle: .lemonade)
    let contentOnColor = Color("lemonade-themed-fuchsia-content-on-color", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-fuchsia-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedGreenColors: ThemedGreenColors {
    let background = Color("lemonade-themed-green-background", bundle: .lemonade)
    let backgroundSubtle = Color("lemonade-themed-green-background-subtle", bundle: .lemonade)
    let border = Color("lemonade-themed-green-border", bundle: .lemonade)
    let borderSubtle = Color("lemonade-themed-green-border-subtle", bundle: .lemonade)
    let content = Color("lemonade-themed-green-content", bundle: .lemonade)
    let contentOnColor = Color("lemonade-themed-green-content-on-color", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-green-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedGreenLimeColors: ThemedGreenLimeColors {
    let background = Color("lemonade-themed-green-lime-background", bundle: .lemonade)
    let backgroundSubtle = Color("lemonade-themed-green-lime-background-subtle", bundle: .lemonade)
    let border = Color("lemonade-themed-green-lime-border", bundle: .lemonade)
    let borderSubtle = Color("lemonade-themed-green-lime-border-subtle", bundle: .lemonade)
    let content = Color("lemonade-themed-green-lime-content", bundle: .lemonade)
    let contentOnColor = Color("lemonade-themed-green-lime-content-on-color", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-green-lime-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedIndigoColors: ThemedIndigoColors {
    let background = Color("lemonade-themed-indigo-background", bundle: .lemonade)
    let backgroundSubtle = Color("lemonade-themed-indigo-background-subtle", bundle: .lemonade)
    let border = Color("lemonade-themed-indigo-border", bundle: .lemonade)
    let borderSubtle = Color("lemonade-themed-indigo-border-subtle", bundle: .lemonade)
    let content = Color("lemonade-themed-indigo-content", bundle: .lemonade)
    let contentOnColor = Color("lemonade-themed-indigo-content-on-color", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-indigo-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedOrangeColors: ThemedOrangeColors {
    let background = Color("lemonade-themed-orange-background", bundle: .lemonade)
    let backgroundSubtle = Color("lemonade-themed-orange-background-subtle", bundle: .lemonade)
    let border = Color("lemonade-themed-orange-border", bundle: .lemonade)
    let borderSubtle = Color("lemonade-themed-orange-border-subtle", bundle: .lemonade)
    let content = Color("lemonade-themed-orange-content", bundle: .lemonade)
    let contentOnColor = Color("lemonade-themed-orange-content-on-color", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-orange-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedPinkColors: ThemedPinkColors {
    let background = Color("lemonade-themed-pink-background", bundle: .lemonade)
    let backgroundSubtle = Color("lemonade-themed-pink-background-subtle", bundle: .lemonade)
    let border = Color("lemonade-themed-pink-border", bundle: .lemonade)
    let borderSubtle = Color("lemonade-themed-pink-border-subtle", bundle: .lemonade)
    let content = Color("lemonade-themed-pink-content", bundle: .lemonade)
    let contentOnColor = Color("lemonade-themed-pink-content-on-color", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-pink-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedPurpleColors: ThemedPurpleColors {
    let background = Color("lemonade-themed-purple-background", bundle: .lemonade)
    let backgroundSubtle = Color("lemonade-themed-purple-background-subtle", bundle: .lemonade)
    let border = Color("lemonade-themed-purple-border", bundle: .lemonade)
    let borderSubtle = Color("lemonade-themed-purple-border-subtle", bundle: .lemonade)
    let content = Color("lemonade-themed-purple-content", bundle: .lemonade)
    let contentOnColor = Color("lemonade-themed-purple-content-on-color", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-purple-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedRedColors: ThemedRedColors {
    let background = Color("lemonade-themed-red-background", bundle: .lemonade)
    let backgroundSubtle = Color("lemonade-themed-red-background-subtle", bundle: .lemonade)
    let border = Color("lemonade-themed-red-border", bundle: .lemonade)
    let borderSubtle = Color("lemonade-themed-red-border-subtle", bundle: .lemonade)
    let content = Color("lemonade-themed-red-content", bundle: .lemonade)
    let contentOnColor = Color("lemonade-themed-red-content-on-color", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-red-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedRoseColors: ThemedRoseColors {
    let background = Color("lemonade-themed-rose-background", bundle: .lemonade)
    let backgroundSubtle = Color("lemonade-themed-rose-background-subtle", bundle: .lemonade)
    let border = Color("lemonade-themed-rose-border", bundle: .lemonade)
    let borderSubtle = Color("lemonade-themed-rose-border-subtle", bundle: .lemonade)
    let content = Color("lemonade-themed-rose-content", bundle: .lemonade)
    let contentOnColor = Color("lemonade-themed-rose-content-on-color", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-rose-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedTealColors: ThemedTealColors {
    let background = Color("lemonade-themed-teal-background", bundle: .lemonade)
    let backgroundSubtle = Color("lemonade-themed-teal-background-subtle", bundle: .lemonade)
    let border = Color("lemonade-themed-teal-border", bundle: .lemonade)
    let borderSubtle = Color("lemonade-themed-teal-border-subtle", bundle: .lemonade)
    let content = Color("lemonade-themed-teal-content", bundle: .lemonade)
    let contentOnColor = Color("lemonade-themed-teal-content-on-color", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-teal-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedVioletColors: ThemedVioletColors {
    let background = Color("lemonade-themed-violet-background", bundle: .lemonade)
    let backgroundSubtle = Color("lemonade-themed-violet-background-subtle", bundle: .lemonade)
    let border = Color("lemonade-themed-violet-border", bundle: .lemonade)
    let borderSubtle = Color("lemonade-themed-violet-border-subtle", bundle: .lemonade)
    let content = Color("lemonade-themed-violet-content", bundle: .lemonade)
    let contentOnColor = Color("lemonade-themed-violet-content-on-color", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-violet-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedYellowColors: ThemedYellowColors {
    let background = Color("lemonade-themed-yellow-background", bundle: .lemonade)
    let backgroundSubtle = Color("lemonade-themed-yellow-background-subtle", bundle: .lemonade)
    let border = Color("lemonade-themed-yellow-border", bundle: .lemonade)
    let borderSubtle = Color("lemonade-themed-yellow-border-subtle", bundle: .lemonade)
    let content = Color("lemonade-themed-yellow-content", bundle: .lemonade)
    let contentOnColor = Color("lemonade-themed-yellow-content-on-color", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-yellow-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedYellowLimeColors: ThemedYellowLimeColors {
    let background = Color("lemonade-themed-yellow-lime-background", bundle: .lemonade)
    let backgroundSubtle = Color("lemonade-themed-yellow-lime-background-subtle", bundle: .lemonade)
    let border = Color("lemonade-themed-yellow-lime-border", bundle: .lemonade)
    let borderSubtle = Color("lemonade-themed-yellow-lime-border-subtle", bundle: .lemonade)
    let content = Color("lemonade-themed-yellow-lime-content", bundle: .lemonade)
    let contentOnColor = Color("lemonade-themed-yellow-lime-content-on-color", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-yellow-lime-on-background", bundle: .lemonade)
}

/// Themed palette implementation - colors resolve automatically via Asset Catalog
public struct LemonadeAdaptiveThemedColors: LemonadeThemedColors {
    public init() {}

    public let amber: ThemedAmberColors = AdaptiveThemedAmberColors()
    public let blue: ThemedBlueColors = AdaptiveThemedBlueColors()
    public let cyan: ThemedCyanColors = AdaptiveThemedCyanColors()
    public let fuchsia: ThemedFuchsiaColors = AdaptiveThemedFuchsiaColors()
    public let green: ThemedGreenColors = AdaptiveThemedGreenColors()
    public let greenLime: ThemedGreenLimeColors = AdaptiveThemedGreenLimeColors()
    public let indigo: ThemedIndigoColors = AdaptiveThemedIndigoColors()
    public let orange: ThemedOrangeColors = AdaptiveThemedOrangeColors()
    public let pink: ThemedPinkColors = AdaptiveThemedPinkColors()
    public let purple: ThemedPurpleColors = AdaptiveThemedPurpleColors()
    public let red: ThemedRedColors = AdaptiveThemedRedColors()
    public let rose: ThemedRoseColors = AdaptiveThemedRoseColors()
    public let teal: ThemedTealColors = AdaptiveThemedTealColors()
    public let violet: ThemedVioletColors = AdaptiveThemedVioletColors()
    public let yellow: ThemedYellowColors = AdaptiveThemedYellowColors()
    public let yellowLime: ThemedYellowLimeColors = AdaptiveThemedYellowLimeColors()
}
