import SwiftUI

/// Adaptive theme that uses Asset Catalog colors with built-in light/dark appearance variants.
///
/// Returns `Color` values from the asset catalog that automatically adapt to the
/// system's current appearance (light/dark mode) without any manual switching.
///
/// Usage:
/// ```swift
/// // Set once at app startup — no need to ever switch
/// LemonadeTheme.colors = LemonadeAdaptiveTheme()
/// ```
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-theme-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-theme-token-converter.main.kts
///  
///  @generated by scripts/swiftui-theme-token-converter.main.kts
/// 

private struct AdaptiveBackgroundColors: BackgroundColors {
    let bgBrand = Color("lemonade-background-brand-bg-brand", bundle: .lemonade)
    let bgBrandElevated = Color("lemonade-background-brand-bg-brand-elevated", bundle: .lemonade)
    let bgBrandHigh = Color("lemonade-background-brand-bg-brand-high", bundle: .lemonade)
    let bgBrandSubtle = Color("lemonade-background-brand-bg-brand-subtle", bundle: .lemonade)
    let bgAlwaysDark = Color("lemonade-background-fixed-bg-always-dark", bundle: .lemonade)
    let bgAlwaysDarkHigh = Color("lemonade-background-fixed-bg-always-dark-high", bundle: .lemonade)
    let bgAlwaysDarkLow = Color("lemonade-background-fixed-bg-always-dark-low", bundle: .lemonade)
    let bgAlwaysDarkMedium = Color("lemonade-background-fixed-bg-always-dark-medium", bundle: .lemonade)
    let bgAlwaysLight = Color("lemonade-background-fixed-bg-always-light", bundle: .lemonade)
    let bgAlwaysLightHigh = Color("lemonade-background-fixed-bg-always-light-high", bundle: .lemonade)
    let bgAlwaysLightLow = Color("lemonade-background-fixed-bg-always-light-low", bundle: .lemonade)
    let bgAlwaysLightMedium = Color("lemonade-background-fixed-bg-always-light-medium", bundle: .lemonade)
    let bgTransparent = Color("lemonade-background-fixed-bg-transparent", bundle: .lemonade)
    let bgTransparentDark = Color("lemonade-background-fixed-bg-transparent-dark", bundle: .lemonade)
    let bgTransparentLight = Color("lemonade-background-fixed-bg-transparent-light", bundle: .lemonade)
    let bgDefaultInverse = Color("lemonade-background-inverse-bg-default-inverse", bundle: .lemonade)
    let bgElevatedInverse = Color("lemonade-background-inverse-bg-elevated-inverse", bundle: .lemonade)
    let bgSubtleInverse = Color("lemonade-background-inverse-bg-subtle-inverse", bundle: .lemonade)
    let bgCaution = Color("lemonade-background-voice-bg-caution", bundle: .lemonade)
    let bgCautionSubtle = Color("lemonade-background-voice-bg-caution-subtle", bundle: .lemonade)
    let bgCritical = Color("lemonade-background-voice-bg-critical", bundle: .lemonade)
    let bgCriticalSubtle = Color("lemonade-background-voice-bg-critical-subtle", bundle: .lemonade)
    let bgFeatured = Color("lemonade-background-voice-bg-featured", bundle: .lemonade)
    let bgFeaturedSubtle = Color("lemonade-background-voice-bg-featured-subtle", bundle: .lemonade)
    let bgInfo = Color("lemonade-background-voice-bg-info", bundle: .lemonade)
    let bgInfoSubtle = Color("lemonade-background-voice-bg-info-subtle", bundle: .lemonade)
    let bgNeutral = Color("lemonade-background-voice-bg-neutral", bundle: .lemonade)
    let bgNeutralSubtle = Color("lemonade-background-voice-bg-neutral-subtle", bundle: .lemonade)
    let bgPositive = Color("lemonade-background-voice-bg-positive", bundle: .lemonade)
    let bgPositiveSubtle = Color("lemonade-background-voice-bg-positive-subtle", bundle: .lemonade)
    let bgDefault = Color("lemonade-background-bg-default", bundle: .lemonade)
    let bgElevated = Color("lemonade-background-bg-elevated", bundle: .lemonade)
    let bgElevatedHigh = Color("lemonade-background-bg-elevated-high", bundle: .lemonade)
    let bgSubtle = Color("lemonade-background-bg-subtle", bundle: .lemonade)
}

private struct AdaptiveBorderColors: BorderColors {
    let borderBrand = Color("lemonade-border-brand-border-brand", bundle: .lemonade)
    let borderOnBrandHigh = Color("lemonade-border-brand-border-on-brand-high", bundle: .lemonade)
    let borderOnBrandLow = Color("lemonade-border-brand-border-on-brand-low", bundle: .lemonade)
    let borderOnBrandMedium = Color("lemonade-border-brand-border-on-brand-medium", bundle: .lemonade)
    let borderAlwaysDark = Color("lemonade-border-fixed-border-always-dark", bundle: .lemonade)
    let borderAlwaysDarkHigh = Color("lemonade-border-fixed-border-always-dark-high", bundle: .lemonade)
    let borderAlwaysDarkLow = Color("lemonade-border-fixed-border-always-dark-low", bundle: .lemonade)
    let borderAlwaysDarkMedium = Color("lemonade-border-fixed-border-always-dark-medium", bundle: .lemonade)
    let borderAlwaysLight = Color("lemonade-border-fixed-border-always-light", bundle: .lemonade)
    let borderAlwaysLightHigh = Color("lemonade-border-fixed-border-always-light-high", bundle: .lemonade)
    let borderAlwaysLightLow = Color("lemonade-border-fixed-border-always-light-low", bundle: .lemonade)
    let borderAlwaysLightMedium = Color("lemonade-border-fixed-border-always-light-medium", bundle: .lemonade)
    let borderBrandInverse = Color("lemonade-border-inverse-border-brand-inverse", bundle: .lemonade)
    let borderNeutralHighInverse = Color("lemonade-border-inverse-border-neutral-high-inverse", bundle: .lemonade)
    let borderNeutralLowInverse = Color("lemonade-border-inverse-border-neutral-low-inverse", bundle: .lemonade)
    let borderNeutralMediumInverse = Color("lemonade-border-inverse-border-neutral-medium-inverse", bundle: .lemonade)
    let borderSelectedInverse = Color("lemonade-border-inverse-border-selected-inverse", bundle: .lemonade)
    let borderCaution = Color("lemonade-border-voice-border-caution", bundle: .lemonade)
    let borderCautionSubtle = Color("lemonade-border-voice-border-caution-subtle", bundle: .lemonade)
    let borderCritical = Color("lemonade-border-voice-border-critical", bundle: .lemonade)
    let borderCriticalSubtle = Color("lemonade-border-voice-border-critical-subtle", bundle: .lemonade)
    let borderFeatured = Color("lemonade-border-voice-border-featured", bundle: .lemonade)
    let borderFeaturedSubtle = Color("lemonade-border-voice-border-featured-subtle", bundle: .lemonade)
    let borderInfo = Color("lemonade-border-voice-border-info", bundle: .lemonade)
    let borderInfoSubtle = Color("lemonade-border-voice-border-info-subtle", bundle: .lemonade)
    let borderPositive = Color("lemonade-border-voice-border-positive", bundle: .lemonade)
    let borderPositiveSubtle = Color("lemonade-border-voice-border-positive-subtle", bundle: .lemonade)
    let borderNeutralHigh = Color("lemonade-border-border-neutral-high", bundle: .lemonade)
    let borderNeutralLow = Color("lemonade-border-border-neutral-low", bundle: .lemonade)
    let borderNeutralMedium = Color("lemonade-border-border-neutral-medium", bundle: .lemonade)
    let borderSelected = Color("lemonade-border-border-selected", bundle: .lemonade)
}

private struct AdaptiveContentColors: ContentColors {
    let contentBrand = Color("lemonade-content-brand-content-brand", bundle: .lemonade)
    let contentBrandHigh = Color("lemonade-content-brand-content-brand-high", bundle: .lemonade)
    let contentOnBrandHigh = Color("lemonade-content-brand-content-on-brand-high", bundle: .lemonade)
    let contentOnBrandLow = Color("lemonade-content-brand-content-on-brand-low", bundle: .lemonade)
    let contentAlwaysDark = Color("lemonade-content-fixed-content-always-dark", bundle: .lemonade)
    let contentAlwaysLight = Color("lemonade-content-fixed-content-always-light", bundle: .lemonade)
    let contentCautionAlwaysOnColor = Color("lemonade-content-fixed-content-caution-always-on-color", bundle: .lemonade)
    let contentCriticalAlwaysOnColor = Color("lemonade-content-fixed-content-critical-always-on-color", bundle: .lemonade)
    let contentInfoAlwaysOnColor = Color("lemonade-content-fixed-content-info-always-on-color", bundle: .lemonade)
    let contentNeutralAlwaysOnColor = Color("lemonade-content-fixed-content-neutral-always-on-color", bundle: .lemonade)
    let contentPositiveAlwaysOnColor = Color("lemonade-content-fixed-content-positive-always-on-color", bundle: .lemonade)
    let contentBrandInverse = Color("lemonade-content-inverse-content-brand-inverse", bundle: .lemonade)
    let contentPrimaryInverse = Color("lemonade-content-inverse-content-primary-inverse", bundle: .lemonade)
    let contentSecondaryInverse = Color("lemonade-content-inverse-content-secondary-inverse", bundle: .lemonade)
    let contentTertiaryInverse = Color("lemonade-content-inverse-content-tertiary-inverse", bundle: .lemonade)
    let contentCautionOnColor = Color("lemonade-content-voice-on color-content-caution-on-color", bundle: .lemonade)
    let contentCriticalOnColor = Color("lemonade-content-voice-on color-content-critical-on-color", bundle: .lemonade)
    let contentFeaturedOnColor = Color("lemonade-content-voice-on color-content-featured-on-color", bundle: .lemonade)
    let contentInfoOnColor = Color("lemonade-content-voice-on color-content-info-on-color", bundle: .lemonade)
    let contentNeutralOnColor = Color("lemonade-content-voice-on color-content-neutral-on-color", bundle: .lemonade)
    let contentPositiveOnColor = Color("lemonade-content-voice-on color-content-positive-on-color", bundle: .lemonade)
    let contentCaution = Color("lemonade-content-voice-content-caution", bundle: .lemonade)
    let contentCritical = Color("lemonade-content-voice-content-critical", bundle: .lemonade)
    let contentFeatured = Color("lemonade-content-voice-content-featured", bundle: .lemonade)
    let contentInfo = Color("lemonade-content-voice-content-info", bundle: .lemonade)
    let contentNeutral = Color("lemonade-content-voice-content-neutral", bundle: .lemonade)
    let contentPositive = Color("lemonade-content-voice-content-positive", bundle: .lemonade)
    let contentPrimary = Color("lemonade-content-content-primary", bundle: .lemonade)
    let contentSecondary = Color("lemonade-content-content-secondary", bundle: .lemonade)
    let contentTertiary = Color("lemonade-content-content-tertiary", bundle: .lemonade)
}

private struct AdaptiveInteractionColors: InteractionColors {
    let bgAlwaysDarkHighInteractive = Color("lemonade-interaction-interactive-background-bg-always-dark-high-interactive", bundle: .lemonade)
    let bgAlwaysDarkLowInteractive = Color("lemonade-interaction-interactive-background-bg-always-dark-low-interactive", bundle: .lemonade)
    let bgAlwaysDarkMediumInteractive = Color("lemonade-interaction-interactive-background-bg-always-dark-medium-interactive", bundle: .lemonade)
    let bgAlwaysLightHighInteractive = Color("lemonade-interaction-interactive-background-bg-always-light-high-interactive", bundle: .lemonade)
    let bgAlwaysLightLowInteractive = Color("lemonade-interaction-interactive-background-bg-always-light-low-interactive", bundle: .lemonade)
    let bgAlwaysLightMediumInteractive = Color("lemonade-interaction-interactive-background-bg-always-light-medium-interactive", bundle: .lemonade)
    let bgBrandElevatedInteractive = Color("lemonade-interaction-interactive-background-bg-brand-elevated-interactive", bundle: .lemonade)
    let bgBrandHighInteractive = Color("lemonade-interaction-interactive-background-bg-brand-high-interactive", bundle: .lemonade)
    let bgBrandInteractive = Color("lemonade-interaction-interactive-background-bg-brand-interactive", bundle: .lemonade)
    let bgCautionInteractive = Color("lemonade-interaction-interactive-background-bg-caution-interactive", bundle: .lemonade)
    let bgCautionSubtleInteractive = Color("lemonade-interaction-interactive-background-bg-caution-subtle-interactive", bundle: .lemonade)
    let bgCriticalInteractive = Color("lemonade-interaction-interactive-background-bg-critical-interactive", bundle: .lemonade)
    let bgCriticalSubtleInteractive = Color("lemonade-interaction-interactive-background-bg-critical-subtle-interactive", bundle: .lemonade)
    let bgDefaultInteractive = Color("lemonade-interaction-interactive-background-bg-default-interactive", bundle: .lemonade)
    let bgElevatedHighInteractive = Color("lemonade-interaction-interactive-background-bg-elevated-high-interactive", bundle: .lemonade)
    let bgElevatedInteractive = Color("lemonade-interaction-interactive-background-bg-elevated-interactive", bundle: .lemonade)
    let bgFeaturedInteractive = Color("lemonade-interaction-interactive-background-bg-featured-interactive", bundle: .lemonade)
    let bgFeaturedSubtleInteractive = Color("lemonade-interaction-interactive-background-bg-featured-subtle-interactive", bundle: .lemonade)
    let bgInfoInteractive = Color("lemonade-interaction-interactive-background-bg-info-interactive", bundle: .lemonade)
    let bgInfoSubtleInteractive = Color("lemonade-interaction-interactive-background-bg-info-subtle-interactive", bundle: .lemonade)
    let bgNeutralInteractive = Color("lemonade-interaction-interactive-background-bg-neutral-interactive", bundle: .lemonade)
    let bgNeutralSubtleInteractive = Color("lemonade-interaction-interactive-background-bg-neutral-subtle-interactive", bundle: .lemonade)
    let bgPositiveInteractive = Color("lemonade-interaction-interactive-background-bg-positive-interactive", bundle: .lemonade)
    let bgPositiveSubtleInteractive = Color("lemonade-interaction-interactive-background-bg-positive-subtle-interactive", bundle: .lemonade)
    let bgSubtleInteractive = Color("lemonade-interaction-interactive-background-bg-subtle-interactive", bundle: .lemonade)
    let bgBrandElevatedPressed = Color("lemonade-interaction-pressed-background-bg-brand-elevated-pressed", bundle: .lemonade)
    let bgBrandHighPressed = Color("lemonade-interaction-pressed-background-bg-brand-high-pressed", bundle: .lemonade)
    let bgBrandPressed = Color("lemonade-interaction-pressed-background-bg-brand-pressed", bundle: .lemonade)
    let bgCautionPressed = Color("lemonade-interaction-pressed-background-bg-caution-pressed", bundle: .lemonade)
    let bgCautionSubtlePressed = Color("lemonade-interaction-pressed-background-bg-caution-subtle-pressed", bundle: .lemonade)
    let bgCriticalPressed = Color("lemonade-interaction-pressed-background-bg-critical-pressed", bundle: .lemonade)
    let bgCriticalSubtlePressed = Color("lemonade-interaction-pressed-background-bg-critical-subtle-pressed", bundle: .lemonade)
    let bgDefaultPressed = Color("lemonade-interaction-pressed-background-bg-default-pressed", bundle: .lemonade)
    let bgElevatedPressed = Color("lemonade-interaction-pressed-background-bg-elevated-pressed", bundle: .lemonade)
    let bgFeaturedPressed = Color("lemonade-interaction-pressed-background-bg-featured-pressed", bundle: .lemonade)
    let bgFeaturedSubtlePressed = Color("lemonade-interaction-pressed-background-bg-featured-subtle-pressed", bundle: .lemonade)
    let bgInfoPressed = Color("lemonade-interaction-pressed-background-bg-info-pressed", bundle: .lemonade)
    let bgInfoSubtlePressed = Color("lemonade-interaction-pressed-background-bg-info-subtle-pressed", bundle: .lemonade)
    let bgNeutralPressed = Color("lemonade-interaction-pressed-background-bg-neutral-pressed", bundle: .lemonade)
    let bgNeutralSubtlePressed = Color("lemonade-interaction-pressed-background-bg-neutral-subtle-pressed", bundle: .lemonade)
    let bgPositivePressed = Color("lemonade-interaction-pressed-background-bg-positive-pressed", bundle: .lemonade)
    let bgPositiveSubtlePressed = Color("lemonade-interaction-pressed-background-bg-positive-subtle-pressed", bundle: .lemonade)
    let bgSubtlePressed = Color("lemonade-interaction-pressed-background-bg-subtle-pressed", bundle: .lemonade)
}

private struct AdaptiveScopedColors: ScopedColors {
    let bgSettlementBusinessDays = Color("lemonade-scoped-settlements-bg-settlement-business-days", bundle: .lemonade)
    let bgSettlementEveryday = Color("lemonade-scoped-settlements-bg-settlement-everyday", bundle: .lemonade)
    let bgSettlementInstant = Color("lemonade-scoped-settlements-bg-settlement-instant", bundle: .lemonade)
    let bgSettlementScheduled = Color("lemonade-scoped-settlements-bg-settlement-scheduled", bundle: .lemonade)
    let contentOnSettlementBusinessDays = Color("lemonade-scoped-settlements-content-on-settlement-business-days", bundle: .lemonade)
    let contentOnSettlementEveryday = Color("lemonade-scoped-settlements-content-on-settlement-everyday", bundle: .lemonade)
    let contentOnSettlementInstant = Color("lemonade-scoped-settlements-content-on-settlement-instant", bundle: .lemonade)
    let contentOnSettlementScheduled = Color("lemonade-scoped-settlements-content-on-settlement-scheduled", bundle: .lemonade)
}

private struct AdaptiveShadowColors: ShadowColors {
    let shadowDefault = Color("lemonade-shadow-shadow-default", bundle: .lemonade)
}

/// Adaptive theme implementation — colors resolve automatically via Asset Catalog
public struct LemonadeAdaptiveTheme: LemonadeSemanticColors {
    public init() {}

    public let background: BackgroundColors = AdaptiveBackgroundColors()
    public let border: BorderColors = AdaptiveBorderColors()
    public let content: ContentColors = AdaptiveContentColors()
    public let interaction: InteractionColors = AdaptiveInteractionColors()
    public let scoped: ScopedColors = AdaptiveScopedColors()
    public let shadow: ShadowColors = AdaptiveShadowColors()
}
