import Foundation

/// Lemonade Design System Brand Logos.
/// Brand logos are loaded from the asset catalog bundled with this module.
/// Use the LemonadeUi.BrandLogo component to display brand logos.
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/svg-asset-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/svg-asset-converter.main.kts
///  
///  @generated by scripts/svg-asset-converter.main.kts
/// 

/// Brand logo token enum
public enum LemonadeBrandLogo: String, CaseIterable {
    case amazon = "amazon"
    case amex = "amex"
    case applePay = "apple-pay"
    case bancomat = "bancomat"
    case cartesBancaires = "cartes-bancaires"
    case diners = "diners"
    case directDebit = "direct-debit"
    case discover = "discover"
    case edenred = "edenred"
    case genericMealOrHealthIssuer = "generic-meal-or-health-issuer"
    case girocard = "girocard"
    case googlePay = "google-pay"
    case jcb = "jcb"
    case maestro = "maestro"
    case mastercard = "mastercard"
    case mbWay = "mb-way"
    case multibanco = "multibanco"
    case nfcLogo = "nfc-logo"
    case pagoBancomat = "pago-bancomat"
    case paypal = "paypal"
    case pluxee = "pluxee"
    case sepa = "sepa"
    case sodexo = "sodexo"
    case unionpay = "unionpay"
    case visa = "visa"
}
