import SwiftUI

/// Themed color tokens from Lemonade DS - Foundations
///
/// A generic, theme-aware hue palette sitting between the primitive ramps and the
/// semantic tokens in `LemonadeSemanticColors`. Use these when a colour carries
/// application meaning the design system does not model - chart series, categories,
/// per-role or per-status accents.
///
/// Prefer a semantic token whenever one fits.
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-themed-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-themed-token-converter.main.kts
///  
///  @generated by scripts/swiftui-themed-token-converter.main.kts
/// 

/// Themed background color definitions
public protocol ThemedBackgroundColors {
    var bgAmber: Color { get }
    var bgAmberSubtle: Color { get }
    var bgBlue: Color { get }
    var bgBlueSubtle: Color { get }
    var bgCyan: Color { get }
    var bgCyanSubtle: Color { get }
    var bgFuchsia: Color { get }
    var bgFuchsiaSubtle: Color { get }
    var bgGreen: Color { get }
    var bgGreenLime: Color { get }
    var bgGreenLimeSubtle: Color { get }
    var bgGreenSubtle: Color { get }
    var bgIndigo: Color { get }
    var bgIndigoSubtle: Color { get }
    var bgOrange: Color { get }
    var bgOrangeSubtle: Color { get }
    var bgPink: Color { get }
    var bgPinkSubtle: Color { get }
    var bgPurple: Color { get }
    var bgPurpleSubtle: Color { get }
    var bgRed: Color { get }
    var bgRedSubtle: Color { get }
    var bgRose: Color { get }
    var bgRoseSubtle: Color { get }
    var bgTeal: Color { get }
    var bgTealSubtle: Color { get }
    var bgViolet: Color { get }
    var bgVioletSubtle: Color { get }
    var bgYellow: Color { get }
    var bgYellowLime: Color { get }
    var bgYellowLimeSubtle: Color { get }
    var bgYellowSubtle: Color { get }
}

/// Themed border color definitions
public protocol ThemedBorderColors {
    var borderAmber: Color { get }
    var borderAmberSubtle: Color { get }
    var borderBlue: Color { get }
    var borderBlueSubtle: Color { get }
    var borderCyan: Color { get }
    var borderCyanSubtle: Color { get }
    var borderFuchsia: Color { get }
    var borderFuchsiaSubtle: Color { get }
    var borderGreen: Color { get }
    var borderGreenLime: Color { get }
    var borderGreenLimeSubtle: Color { get }
    var borderGreenSubtle: Color { get }
    var borderIndigo: Color { get }
    var borderIndigoSubtle: Color { get }
    var borderOrange: Color { get }
    var borderOrangeSubtle: Color { get }
    var borderPink: Color { get }
    var borderPinkSubtle: Color { get }
    var borderPurple: Color { get }
    var borderPurpleSubtle: Color { get }
    var borderRed: Color { get }
    var borderRedSubtle: Color { get }
    var borderRose: Color { get }
    var borderRoseSubtle: Color { get }
    var borderTeal: Color { get }
    var borderTealSubtle: Color { get }
    var borderViolet: Color { get }
    var borderVioletSubtle: Color { get }
    var borderYellow: Color { get }
    var borderYellowLime: Color { get }
    var borderYellowLimeSubtle: Color { get }
    var borderYellowSubtle: Color { get }
}

/// Themed content color definitions
public protocol ThemedContentColors {
    var contentAmber: Color { get }
    var contentAmberOnColor: Color { get }
    var contentBlue: Color { get }
    var contentBlueOnColor: Color { get }
    var contentCyan: Color { get }
    var contentCyanOnColor: Color { get }
    var contentFuchsia: Color { get }
    var contentFuchsiaOnColor: Color { get }
    var contentGreen: Color { get }
    var contentGreenLime: Color { get }
    var contentGreenLimeOnColor: Color { get }
    var contentGreenOnColor: Color { get }
    var contentIndigo: Color { get }
    var contentIndigoOnColor: Color { get }
    var contentOnAmber: Color { get }
    var contentOnBlue: Color { get }
    var contentOnCyan: Color { get }
    var contentOnFuchsia: Color { get }
    var contentOnGreen: Color { get }
    var contentOnGreenLime: Color { get }
    var contentOnIndigo: Color { get }
    var contentOnOrange: Color { get }
    var contentOnPink: Color { get }
    var contentOnPurple: Color { get }
    var contentOnRed: Color { get }
    var contentOnRose: Color { get }
    var contentOnTeal: Color { get }
    var contentOnViolet: Color { get }
    var contentOnYellow: Color { get }
    var contentOnYellowLime: Color { get }
    var contentOrange: Color { get }
    var contentOrangeOnColor: Color { get }
    var contentPink: Color { get }
    var contentPinkOnColor: Color { get }
    var contentPurple: Color { get }
    var contentPurpleOnColor: Color { get }
    var contentRed: Color { get }
    var contentRedOnColor: Color { get }
    var contentRose: Color { get }
    var contentRoseOnColor: Color { get }
    var contentTeal: Color { get }
    var contentTealOnColor: Color { get }
    var contentViolet: Color { get }
    var contentVioletOnColor: Color { get }
    var contentYellow: Color { get }
    var contentYellowLime: Color { get }
    var contentYellowLimeOnColor: Color { get }
    var contentYellowOnColor: Color { get }
}

/// Protocol defining themed color categories
public protocol LemonadeThemedColors {
    var background: ThemedBackgroundColors { get }
    var border: ThemedBorderColors { get }
    var content: ThemedContentColors { get }
}

private struct AdaptiveThemedBackgroundColors: ThemedBackgroundColors {
    let bgAmber = Color("lemonade-themed-background-bg-amber", bundle: .lemonade)
    let bgAmberSubtle = Color("lemonade-themed-background-bg-amber-subtle", bundle: .lemonade)
    let bgBlue = Color("lemonade-themed-background-bg-blue", bundle: .lemonade)
    let bgBlueSubtle = Color("lemonade-themed-background-bg-blue-subtle", bundle: .lemonade)
    let bgCyan = Color("lemonade-themed-background-bg-cyan", bundle: .lemonade)
    let bgCyanSubtle = Color("lemonade-themed-background-bg-cyan-subtle", bundle: .lemonade)
    let bgFuchsia = Color("lemonade-themed-background-bg-fuchsia", bundle: .lemonade)
    let bgFuchsiaSubtle = Color("lemonade-themed-background-bg-fuchsia-subtle", bundle: .lemonade)
    let bgGreen = Color("lemonade-themed-background-bg-green", bundle: .lemonade)
    let bgGreenLime = Color("lemonade-themed-background-bg-green-lime", bundle: .lemonade)
    let bgGreenLimeSubtle = Color("lemonade-themed-background-bg-green-lime-subtle", bundle: .lemonade)
    let bgGreenSubtle = Color("lemonade-themed-background-bg-green-subtle", bundle: .lemonade)
    let bgIndigo = Color("lemonade-themed-background-bg-indigo", bundle: .lemonade)
    let bgIndigoSubtle = Color("lemonade-themed-background-bg-indigo-subtle", bundle: .lemonade)
    let bgOrange = Color("lemonade-themed-background-bg-orange", bundle: .lemonade)
    let bgOrangeSubtle = Color("lemonade-themed-background-bg-orange-subtle", bundle: .lemonade)
    let bgPink = Color("lemonade-themed-background-bg-pink", bundle: .lemonade)
    let bgPinkSubtle = Color("lemonade-themed-background-bg-pink-subtle", bundle: .lemonade)
    let bgPurple = Color("lemonade-themed-background-bg-purple", bundle: .lemonade)
    let bgPurpleSubtle = Color("lemonade-themed-background-bg-purple-subtle", bundle: .lemonade)
    let bgRed = Color("lemonade-themed-background-bg-red", bundle: .lemonade)
    let bgRedSubtle = Color("lemonade-themed-background-bg-red-subtle", bundle: .lemonade)
    let bgRose = Color("lemonade-themed-background-bg-rose", bundle: .lemonade)
    let bgRoseSubtle = Color("lemonade-themed-background-bg-rose-subtle", bundle: .lemonade)
    let bgTeal = Color("lemonade-themed-background-bg-teal", bundle: .lemonade)
    let bgTealSubtle = Color("lemonade-themed-background-bg-teal-subtle", bundle: .lemonade)
    let bgViolet = Color("lemonade-themed-background-bg-violet", bundle: .lemonade)
    let bgVioletSubtle = Color("lemonade-themed-background-bg-violet-subtle", bundle: .lemonade)
    let bgYellow = Color("lemonade-themed-background-bg-yellow", bundle: .lemonade)
    let bgYellowLime = Color("lemonade-themed-background-bg-yellow-lime", bundle: .lemonade)
    let bgYellowLimeSubtle = Color("lemonade-themed-background-bg-yellow-lime-subtle", bundle: .lemonade)
    let bgYellowSubtle = Color("lemonade-themed-background-bg-yellow-subtle", bundle: .lemonade)
}

private struct AdaptiveThemedBorderColors: ThemedBorderColors {
    let borderAmber = Color("lemonade-themed-border-border-amber", bundle: .lemonade)
    let borderAmberSubtle = Color("lemonade-themed-border-border-amber-subtle", bundle: .lemonade)
    let borderBlue = Color("lemonade-themed-border-border-blue", bundle: .lemonade)
    let borderBlueSubtle = Color("lemonade-themed-border-border-blue-subtle", bundle: .lemonade)
    let borderCyan = Color("lemonade-themed-border-border-cyan", bundle: .lemonade)
    let borderCyanSubtle = Color("lemonade-themed-border-border-cyan-subtle", bundle: .lemonade)
    let borderFuchsia = Color("lemonade-themed-border-border-fuchsia", bundle: .lemonade)
    let borderFuchsiaSubtle = Color("lemonade-themed-border-border-fuchsia-subtle", bundle: .lemonade)
    let borderGreen = Color("lemonade-themed-border-border-green", bundle: .lemonade)
    let borderGreenLime = Color("lemonade-themed-border-border-green-lime", bundle: .lemonade)
    let borderGreenLimeSubtle = Color("lemonade-themed-border-border-green-lime-subtle", bundle: .lemonade)
    let borderGreenSubtle = Color("lemonade-themed-border-border-green-subtle", bundle: .lemonade)
    let borderIndigo = Color("lemonade-themed-border-border-indigo", bundle: .lemonade)
    let borderIndigoSubtle = Color("lemonade-themed-border-border-indigo-subtle", bundle: .lemonade)
    let borderOrange = Color("lemonade-themed-border-border-orange", bundle: .lemonade)
    let borderOrangeSubtle = Color("lemonade-themed-border-border-orange-subtle", bundle: .lemonade)
    let borderPink = Color("lemonade-themed-border-border-pink", bundle: .lemonade)
    let borderPinkSubtle = Color("lemonade-themed-border-border-pink-subtle", bundle: .lemonade)
    let borderPurple = Color("lemonade-themed-border-border-purple", bundle: .lemonade)
    let borderPurpleSubtle = Color("lemonade-themed-border-border-purple-subtle", bundle: .lemonade)
    let borderRed = Color("lemonade-themed-border-border-red", bundle: .lemonade)
    let borderRedSubtle = Color("lemonade-themed-border-border-red-subtle", bundle: .lemonade)
    let borderRose = Color("lemonade-themed-border-border-rose", bundle: .lemonade)
    let borderRoseSubtle = Color("lemonade-themed-border-border-rose-subtle", bundle: .lemonade)
    let borderTeal = Color("lemonade-themed-border-border-teal", bundle: .lemonade)
    let borderTealSubtle = Color("lemonade-themed-border-border-teal-subtle", bundle: .lemonade)
    let borderViolet = Color("lemonade-themed-border-border-violet", bundle: .lemonade)
    let borderVioletSubtle = Color("lemonade-themed-border-border-violet-subtle", bundle: .lemonade)
    let borderYellow = Color("lemonade-themed-border-border-yellow", bundle: .lemonade)
    let borderYellowLime = Color("lemonade-themed-border-border-yellow-lime", bundle: .lemonade)
    let borderYellowLimeSubtle = Color("lemonade-themed-border-border-yellow-lime-subtle", bundle: .lemonade)
    let borderYellowSubtle = Color("lemonade-themed-border-border-yellow-subtle", bundle: .lemonade)
}

private struct AdaptiveThemedContentColors: ThemedContentColors {
    let contentAmber = Color("lemonade-themed-content-content-amber", bundle: .lemonade)
    let contentAmberOnColor = Color("lemonade-themed-content-content-amber-on-color", bundle: .lemonade)
    let contentBlue = Color("lemonade-themed-content-content-blue", bundle: .lemonade)
    let contentBlueOnColor = Color("lemonade-themed-content-content-blue-on-color", bundle: .lemonade)
    let contentCyan = Color("lemonade-themed-content-content-cyan", bundle: .lemonade)
    let contentCyanOnColor = Color("lemonade-themed-content-content-cyan-on-color", bundle: .lemonade)
    let contentFuchsia = Color("lemonade-themed-content-content-fuchsia", bundle: .lemonade)
    let contentFuchsiaOnColor = Color("lemonade-themed-content-content-fuchsia-on-color", bundle: .lemonade)
    let contentGreen = Color("lemonade-themed-content-content-green", bundle: .lemonade)
    let contentGreenLime = Color("lemonade-themed-content-content-green-lime", bundle: .lemonade)
    let contentGreenLimeOnColor = Color("lemonade-themed-content-content-green-lime-on-color", bundle: .lemonade)
    let contentGreenOnColor = Color("lemonade-themed-content-content-green-on-color", bundle: .lemonade)
    let contentIndigo = Color("lemonade-themed-content-content-indigo", bundle: .lemonade)
    let contentIndigoOnColor = Color("lemonade-themed-content-content-indigo-on-color", bundle: .lemonade)
    let contentOnAmber = Color("lemonade-themed-content-content-on-amber", bundle: .lemonade)
    let contentOnBlue = Color("lemonade-themed-content-content-on-blue", bundle: .lemonade)
    let contentOnCyan = Color("lemonade-themed-content-content-on-cyan", bundle: .lemonade)
    let contentOnFuchsia = Color("lemonade-themed-content-content-on-fuchsia", bundle: .lemonade)
    let contentOnGreen = Color("lemonade-themed-content-content-on-green", bundle: .lemonade)
    let contentOnGreenLime = Color("lemonade-themed-content-content-on-green-lime", bundle: .lemonade)
    let contentOnIndigo = Color("lemonade-themed-content-content-on-indigo", bundle: .lemonade)
    let contentOnOrange = Color("lemonade-themed-content-content-on-orange", bundle: .lemonade)
    let contentOnPink = Color("lemonade-themed-content-content-on-pink", bundle: .lemonade)
    let contentOnPurple = Color("lemonade-themed-content-content-on-purple", bundle: .lemonade)
    let contentOnRed = Color("lemonade-themed-content-content-on-red", bundle: .lemonade)
    let contentOnRose = Color("lemonade-themed-content-content-on-rose", bundle: .lemonade)
    let contentOnTeal = Color("lemonade-themed-content-content-on-teal", bundle: .lemonade)
    let contentOnViolet = Color("lemonade-themed-content-content-on-violet", bundle: .lemonade)
    let contentOnYellow = Color("lemonade-themed-content-content-on-yellow", bundle: .lemonade)
    let contentOnYellowLime = Color("lemonade-themed-content-content-on-yellow-lime", bundle: .lemonade)
    let contentOrange = Color("lemonade-themed-content-content-orange", bundle: .lemonade)
    let contentOrangeOnColor = Color("lemonade-themed-content-content-orange-on-color", bundle: .lemonade)
    let contentPink = Color("lemonade-themed-content-content-pink", bundle: .lemonade)
    let contentPinkOnColor = Color("lemonade-themed-content-content-pink-on-color", bundle: .lemonade)
    let contentPurple = Color("lemonade-themed-content-content-purple", bundle: .lemonade)
    let contentPurpleOnColor = Color("lemonade-themed-content-content-purple-on-color", bundle: .lemonade)
    let contentRed = Color("lemonade-themed-content-content-red", bundle: .lemonade)
    let contentRedOnColor = Color("lemonade-themed-content-content-red-on-color", bundle: .lemonade)
    let contentRose = Color("lemonade-themed-content-content-rose", bundle: .lemonade)
    let contentRoseOnColor = Color("lemonade-themed-content-content-rose-on-color", bundle: .lemonade)
    let contentTeal = Color("lemonade-themed-content-content-teal", bundle: .lemonade)
    let contentTealOnColor = Color("lemonade-themed-content-content-teal-on-color", bundle: .lemonade)
    let contentViolet = Color("lemonade-themed-content-content-violet", bundle: .lemonade)
    let contentVioletOnColor = Color("lemonade-themed-content-content-violet-on-color", bundle: .lemonade)
    let contentYellow = Color("lemonade-themed-content-content-yellow", bundle: .lemonade)
    let contentYellowLime = Color("lemonade-themed-content-content-yellow-lime", bundle: .lemonade)
    let contentYellowLimeOnColor = Color("lemonade-themed-content-content-yellow-lime-on-color", bundle: .lemonade)
    let contentYellowOnColor = Color("lemonade-themed-content-content-yellow-on-color", bundle: .lemonade)
}

/// Themed palette implementation - colors resolve automatically via Asset Catalog
public struct LemonadeAdaptiveThemedColors: LemonadeThemedColors {
    public init() {}

    public let background: ThemedBackgroundColors = AdaptiveThemedBackgroundColors()
    public let border: ThemedBorderColors = AdaptiveThemedBorderColors()
    public let content: ThemedContentColors = AdaptiveThemedContentColors()
}
