import SwiftUI

/// Themed color tokens from Lemonade DS - Foundations
///
/// A generic, theme-aware hue palette sitting between the primitive ramps and the
/// semantic tokens in `LemonadeSemanticColors`. Use these when a colour carries
/// application meaning the design system does not model - chart series, categories,
/// per-role or per-status accents.
///
/// Each hue carries a saturated palette and a `subtle` one, so a component can hold
/// either as a `ThemedColor` and style itself from it.
///
/// Prefer a semantic token whenever one fits.
///
/// > Experimental: the shape of this layer is still settling and may change
/// > without a deprecation cycle. The KMP side gates this behind
/// > `@OptIn(ExperimentalLemonadeApi::class)`; Swift has no equivalent, so
/// > treat it as opt-in by convention and expect to revisit call sites.
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-themed-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-themed-token-converter.main.kts
///  
///  @generated by scripts/swiftui-themed-token-converter.main.kts
/// 

/// The slots every themed palette provides, saturated or subtle alike, so one can be
/// passed around as a value - a chart series, a per-role accent, a category.
///
/// ```swift
/// let style: ThemedColor = subtle ? LemonadeTheme.themed.blue.subtle : LemonadeTheme.themed.blue
/// ```
public protocol ThemedColor {
    var background: Color { get }
    var border: Color { get }
    var onBackground: Color { get }
}

/// A hue's saturated palette. Adds the slots that only make sense on the hue itself,
/// plus its `subtle` counterpart.
public protocol ThemedPrimaryColor: ThemedColor {
    var content: Color { get }
    var contentInverse: Color { get }
    var subtle: ThemedColor { get }
}

/// Themed amber color definitions
public protocol ThemedAmberColors: ThemedPrimaryColor {}

/// Themed blue color definitions
public protocol ThemedBlueColors: ThemedPrimaryColor {}

/// Themed cyan color definitions
public protocol ThemedCyanColors: ThemedPrimaryColor {}

/// Themed fuchsia color definitions
public protocol ThemedFuchsiaColors: ThemedPrimaryColor {}

/// Themed green color definitions
public protocol ThemedGreenColors: ThemedPrimaryColor {}

/// Themed greenlime color definitions
public protocol ThemedGreenLimeColors: ThemedPrimaryColor {}

/// Themed indigo color definitions
public protocol ThemedIndigoColors: ThemedPrimaryColor {}

/// Themed neutral color definitions
public protocol ThemedNeutralColors: ThemedPrimaryColor {}

/// Themed orange color definitions
public protocol ThemedOrangeColors: ThemedPrimaryColor {}

/// Themed pink color definitions
public protocol ThemedPinkColors: ThemedPrimaryColor {}

/// Themed purple color definitions
public protocol ThemedPurpleColors: ThemedPrimaryColor {}

/// Themed red color definitions
public protocol ThemedRedColors: ThemedPrimaryColor {}

/// Themed rose color definitions
public protocol ThemedRoseColors: ThemedPrimaryColor {}

/// Themed teal color definitions
public protocol ThemedTealColors: ThemedPrimaryColor {}

/// Themed violet color definitions
public protocol ThemedVioletColors: ThemedPrimaryColor {}

/// Themed yellow color definitions
public protocol ThemedYellowColors: ThemedPrimaryColor {}

/// Themed yellowlime color definitions
public protocol ThemedYellowLimeColors: ThemedPrimaryColor {}

/// Protocol defining themed color categories
public protocol LemonadeThemedColors {
    var amber: ThemedAmberColors { get }
    var blue: ThemedBlueColors { get }
    var cyan: ThemedCyanColors { get }
    var fuchsia: ThemedFuchsiaColors { get }
    var green: ThemedGreenColors { get }
    var greenLime: ThemedGreenLimeColors { get }
    var indigo: ThemedIndigoColors { get }
    var neutral: ThemedNeutralColors { get }
    var orange: ThemedOrangeColors { get }
    var pink: ThemedPinkColors { get }
    var purple: ThemedPurpleColors { get }
    var red: ThemedRedColors { get }
    var rose: ThemedRoseColors { get }
    var teal: ThemedTealColors { get }
    var violet: ThemedVioletColors { get }
    var yellow: ThemedYellowColors { get }
    var yellowLime: ThemedYellowLimeColors { get }
}

private struct AdaptiveThemedAmberSubtleColors: ThemedColor {
    let background = Color("lemonade-themed-amber-subtle-background", bundle: .lemonade)
    let border = Color("lemonade-themed-amber-subtle-border", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-amber-subtle-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedAmberColors: ThemedAmberColors {
    let background = Color("lemonade-themed-amber-background", bundle: .lemonade)
    let border = Color("lemonade-themed-amber-border", bundle: .lemonade)
    let content = Color("lemonade-themed-amber-content", bundle: .lemonade)
    let contentInverse = Color("lemonade-themed-amber-content-inverse", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-amber-on-background", bundle: .lemonade)
    let subtle: ThemedColor = AdaptiveThemedAmberSubtleColors()
}

private struct AdaptiveThemedBlueSubtleColors: ThemedColor {
    let background = Color("lemonade-themed-blue-subtle-background", bundle: .lemonade)
    let border = Color("lemonade-themed-blue-subtle-border", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-blue-subtle-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedBlueColors: ThemedBlueColors {
    let background = Color("lemonade-themed-blue-background", bundle: .lemonade)
    let border = Color("lemonade-themed-blue-border", bundle: .lemonade)
    let content = Color("lemonade-themed-blue-content", bundle: .lemonade)
    let contentInverse = Color("lemonade-themed-blue-content-inverse", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-blue-on-background", bundle: .lemonade)
    let subtle: ThemedColor = AdaptiveThemedBlueSubtleColors()
}

private struct AdaptiveThemedCyanSubtleColors: ThemedColor {
    let background = Color("lemonade-themed-cyan-subtle-background", bundle: .lemonade)
    let border = Color("lemonade-themed-cyan-subtle-border", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-cyan-subtle-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedCyanColors: ThemedCyanColors {
    let background = Color("lemonade-themed-cyan-background", bundle: .lemonade)
    let border = Color("lemonade-themed-cyan-border", bundle: .lemonade)
    let content = Color("lemonade-themed-cyan-content", bundle: .lemonade)
    let contentInverse = Color("lemonade-themed-cyan-content-inverse", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-cyan-on-background", bundle: .lemonade)
    let subtle: ThemedColor = AdaptiveThemedCyanSubtleColors()
}

private struct AdaptiveThemedFuchsiaSubtleColors: ThemedColor {
    let background = Color("lemonade-themed-fuchsia-subtle-background", bundle: .lemonade)
    let border = Color("lemonade-themed-fuchsia-subtle-border", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-fuchsia-subtle-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedFuchsiaColors: ThemedFuchsiaColors {
    let background = Color("lemonade-themed-fuchsia-background", bundle: .lemonade)
    let border = Color("lemonade-themed-fuchsia-border", bundle: .lemonade)
    let content = Color("lemonade-themed-fuchsia-content", bundle: .lemonade)
    let contentInverse = Color("lemonade-themed-fuchsia-content-inverse", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-fuchsia-on-background", bundle: .lemonade)
    let subtle: ThemedColor = AdaptiveThemedFuchsiaSubtleColors()
}

private struct AdaptiveThemedGreenSubtleColors: ThemedColor {
    let background = Color("lemonade-themed-green-subtle-background", bundle: .lemonade)
    let border = Color("lemonade-themed-green-subtle-border", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-green-subtle-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedGreenColors: ThemedGreenColors {
    let background = Color("lemonade-themed-green-background", bundle: .lemonade)
    let border = Color("lemonade-themed-green-border", bundle: .lemonade)
    let content = Color("lemonade-themed-green-content", bundle: .lemonade)
    let contentInverse = Color("lemonade-themed-green-content-inverse", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-green-on-background", bundle: .lemonade)
    let subtle: ThemedColor = AdaptiveThemedGreenSubtleColors()
}

private struct AdaptiveThemedGreenLimeSubtleColors: ThemedColor {
    let background = Color("lemonade-themed-green-lime-subtle-background", bundle: .lemonade)
    let border = Color("lemonade-themed-green-lime-subtle-border", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-green-lime-subtle-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedGreenLimeColors: ThemedGreenLimeColors {
    let background = Color("lemonade-themed-green-lime-background", bundle: .lemonade)
    let border = Color("lemonade-themed-green-lime-border", bundle: .lemonade)
    let content = Color("lemonade-themed-green-lime-content", bundle: .lemonade)
    let contentInverse = Color("lemonade-themed-green-lime-content-inverse", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-green-lime-on-background", bundle: .lemonade)
    let subtle: ThemedColor = AdaptiveThemedGreenLimeSubtleColors()
}

private struct AdaptiveThemedIndigoSubtleColors: ThemedColor {
    let background = Color("lemonade-themed-indigo-subtle-background", bundle: .lemonade)
    let border = Color("lemonade-themed-indigo-subtle-border", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-indigo-subtle-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedIndigoColors: ThemedIndigoColors {
    let background = Color("lemonade-themed-indigo-background", bundle: .lemonade)
    let border = Color("lemonade-themed-indigo-border", bundle: .lemonade)
    let content = Color("lemonade-themed-indigo-content", bundle: .lemonade)
    let contentInverse = Color("lemonade-themed-indigo-content-inverse", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-indigo-on-background", bundle: .lemonade)
    let subtle: ThemedColor = AdaptiveThemedIndigoSubtleColors()
}

private struct AdaptiveThemedNeutralSubtleColors: ThemedColor {
    let background = Color("lemonade-themed-neutral-subtle-background", bundle: .lemonade)
    let border = Color("lemonade-themed-neutral-subtle-border", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-neutral-subtle-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedNeutralColors: ThemedNeutralColors {
    let background = Color("lemonade-themed-neutral-background", bundle: .lemonade)
    let border = Color("lemonade-themed-neutral-border", bundle: .lemonade)
    let content = Color("lemonade-themed-neutral-content", bundle: .lemonade)
    let contentInverse = Color("lemonade-themed-neutral-content-inverse", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-neutral-on-background", bundle: .lemonade)
    let subtle: ThemedColor = AdaptiveThemedNeutralSubtleColors()
}

private struct AdaptiveThemedOrangeSubtleColors: ThemedColor {
    let background = Color("lemonade-themed-orange-subtle-background", bundle: .lemonade)
    let border = Color("lemonade-themed-orange-subtle-border", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-orange-subtle-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedOrangeColors: ThemedOrangeColors {
    let background = Color("lemonade-themed-orange-background", bundle: .lemonade)
    let border = Color("lemonade-themed-orange-border", bundle: .lemonade)
    let content = Color("lemonade-themed-orange-content", bundle: .lemonade)
    let contentInverse = Color("lemonade-themed-orange-content-inverse", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-orange-on-background", bundle: .lemonade)
    let subtle: ThemedColor = AdaptiveThemedOrangeSubtleColors()
}

private struct AdaptiveThemedPinkSubtleColors: ThemedColor {
    let background = Color("lemonade-themed-pink-subtle-background", bundle: .lemonade)
    let border = Color("lemonade-themed-pink-subtle-border", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-pink-subtle-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedPinkColors: ThemedPinkColors {
    let background = Color("lemonade-themed-pink-background", bundle: .lemonade)
    let border = Color("lemonade-themed-pink-border", bundle: .lemonade)
    let content = Color("lemonade-themed-pink-content", bundle: .lemonade)
    let contentInverse = Color("lemonade-themed-pink-content-inverse", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-pink-on-background", bundle: .lemonade)
    let subtle: ThemedColor = AdaptiveThemedPinkSubtleColors()
}

private struct AdaptiveThemedPurpleSubtleColors: ThemedColor {
    let background = Color("lemonade-themed-purple-subtle-background", bundle: .lemonade)
    let border = Color("lemonade-themed-purple-subtle-border", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-purple-subtle-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedPurpleColors: ThemedPurpleColors {
    let background = Color("lemonade-themed-purple-background", bundle: .lemonade)
    let border = Color("lemonade-themed-purple-border", bundle: .lemonade)
    let content = Color("lemonade-themed-purple-content", bundle: .lemonade)
    let contentInverse = Color("lemonade-themed-purple-content-inverse", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-purple-on-background", bundle: .lemonade)
    let subtle: ThemedColor = AdaptiveThemedPurpleSubtleColors()
}

private struct AdaptiveThemedRedSubtleColors: ThemedColor {
    let background = Color("lemonade-themed-red-subtle-background", bundle: .lemonade)
    let border = Color("lemonade-themed-red-subtle-border", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-red-subtle-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedRedColors: ThemedRedColors {
    let background = Color("lemonade-themed-red-background", bundle: .lemonade)
    let border = Color("lemonade-themed-red-border", bundle: .lemonade)
    let content = Color("lemonade-themed-red-content", bundle: .lemonade)
    let contentInverse = Color("lemonade-themed-red-content-inverse", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-red-on-background", bundle: .lemonade)
    let subtle: ThemedColor = AdaptiveThemedRedSubtleColors()
}

private struct AdaptiveThemedRoseSubtleColors: ThemedColor {
    let background = Color("lemonade-themed-rose-subtle-background", bundle: .lemonade)
    let border = Color("lemonade-themed-rose-subtle-border", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-rose-subtle-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedRoseColors: ThemedRoseColors {
    let background = Color("lemonade-themed-rose-background", bundle: .lemonade)
    let border = Color("lemonade-themed-rose-border", bundle: .lemonade)
    let content = Color("lemonade-themed-rose-content", bundle: .lemonade)
    let contentInverse = Color("lemonade-themed-rose-content-inverse", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-rose-on-background", bundle: .lemonade)
    let subtle: ThemedColor = AdaptiveThemedRoseSubtleColors()
}

private struct AdaptiveThemedTealSubtleColors: ThemedColor {
    let background = Color("lemonade-themed-teal-subtle-background", bundle: .lemonade)
    let border = Color("lemonade-themed-teal-subtle-border", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-teal-subtle-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedTealColors: ThemedTealColors {
    let background = Color("lemonade-themed-teal-background", bundle: .lemonade)
    let border = Color("lemonade-themed-teal-border", bundle: .lemonade)
    let content = Color("lemonade-themed-teal-content", bundle: .lemonade)
    let contentInverse = Color("lemonade-themed-teal-content-inverse", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-teal-on-background", bundle: .lemonade)
    let subtle: ThemedColor = AdaptiveThemedTealSubtleColors()
}

private struct AdaptiveThemedVioletSubtleColors: ThemedColor {
    let background = Color("lemonade-themed-violet-subtle-background", bundle: .lemonade)
    let border = Color("lemonade-themed-violet-subtle-border", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-violet-subtle-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedVioletColors: ThemedVioletColors {
    let background = Color("lemonade-themed-violet-background", bundle: .lemonade)
    let border = Color("lemonade-themed-violet-border", bundle: .lemonade)
    let content = Color("lemonade-themed-violet-content", bundle: .lemonade)
    let contentInverse = Color("lemonade-themed-violet-content-inverse", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-violet-on-background", bundle: .lemonade)
    let subtle: ThemedColor = AdaptiveThemedVioletSubtleColors()
}

private struct AdaptiveThemedYellowSubtleColors: ThemedColor {
    let background = Color("lemonade-themed-yellow-subtle-background", bundle: .lemonade)
    let border = Color("lemonade-themed-yellow-subtle-border", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-yellow-subtle-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedYellowColors: ThemedYellowColors {
    let background = Color("lemonade-themed-yellow-background", bundle: .lemonade)
    let border = Color("lemonade-themed-yellow-border", bundle: .lemonade)
    let content = Color("lemonade-themed-yellow-content", bundle: .lemonade)
    let contentInverse = Color("lemonade-themed-yellow-content-inverse", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-yellow-on-background", bundle: .lemonade)
    let subtle: ThemedColor = AdaptiveThemedYellowSubtleColors()
}

private struct AdaptiveThemedYellowLimeSubtleColors: ThemedColor {
    let background = Color("lemonade-themed-yellow-lime-subtle-background", bundle: .lemonade)
    let border = Color("lemonade-themed-yellow-lime-subtle-border", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-yellow-lime-subtle-on-background", bundle: .lemonade)
}

private struct AdaptiveThemedYellowLimeColors: ThemedYellowLimeColors {
    let background = Color("lemonade-themed-yellow-lime-background", bundle: .lemonade)
    let border = Color("lemonade-themed-yellow-lime-border", bundle: .lemonade)
    let content = Color("lemonade-themed-yellow-lime-content", bundle: .lemonade)
    let contentInverse = Color("lemonade-themed-yellow-lime-content-inverse", bundle: .lemonade)
    let onBackground = Color("lemonade-themed-yellow-lime-on-background", bundle: .lemonade)
    let subtle: ThemedColor = AdaptiveThemedYellowLimeSubtleColors()
}

/// Themed palette implementation - colors resolve automatically via Asset Catalog
public struct LemonadeAdaptiveThemedColors: LemonadeThemedColors {
    public init() {}

    public let amber: ThemedAmberColors = AdaptiveThemedAmberColors()
    public let blue: ThemedBlueColors = AdaptiveThemedBlueColors()
    public let cyan: ThemedCyanColors = AdaptiveThemedCyanColors()
    public let fuchsia: ThemedFuchsiaColors = AdaptiveThemedFuchsiaColors()
    public let green: ThemedGreenColors = AdaptiveThemedGreenColors()
    public let greenLime: ThemedGreenLimeColors = AdaptiveThemedGreenLimeColors()
    public let indigo: ThemedIndigoColors = AdaptiveThemedIndigoColors()
    public let neutral: ThemedNeutralColors = AdaptiveThemedNeutralColors()
    public let orange: ThemedOrangeColors = AdaptiveThemedOrangeColors()
    public let pink: ThemedPinkColors = AdaptiveThemedPinkColors()
    public let purple: ThemedPurpleColors = AdaptiveThemedPurpleColors()
    public let red: ThemedRedColors = AdaptiveThemedRedColors()
    public let rose: ThemedRoseColors = AdaptiveThemedRoseColors()
    public let teal: ThemedTealColors = AdaptiveThemedTealColors()
    public let violet: ThemedVioletColors = AdaptiveThemedVioletColors()
    public let yellow: ThemedYellowColors = AdaptiveThemedYellowColors()
    public let yellowLime: ThemedYellowLimeColors = AdaptiveThemedYellowLimeColors()
}
