// DO NOT MODIFY THIS FILE MANUALLY — generated by scripts/generate-asset-templates.mjs
// url=<LEMONADE_COMPONENTS>?node-id=21423-824
// source=kmp/core/src/commonMain/kotlin/com/teya/lemonade/core/LemonadeBrandLogos.kt
// component=LemonadeBrandLogos
import figma from 'figma'

export default {
  example: figma.kotlin`LemonadeBrandLogos.PagoBancomat`,
  imports: ['import com.teya.lemonade.core.LemonadeBrandLogos'],
  id: 'brandLogo-pago-bancomat-dark',
  metadata: { nestable: true },
}
