// DO NOT MODIFY THIS FILE MANUALLY — generated by scripts/generate-asset-templates.mjs
// url=<LEMONADE_ICONS>?node-id=4526-66
// source=swiftui/Sources/Lemonade/LemonadeIcons.swift
// component=LemonadeIcon
import figma from 'figma'

export default {
  example: figma.swift`LemonadeIcon.brandTeyaPos`,
  id: 'icon-brand-teya-pos',
  metadata: { nestable: true },
}
