// DO NOT MODIFY THIS FILE MANUALLY — generated by scripts/generate-asset-templates.mjs
// url=<LEMONADE_ICONS>?node-id=3230-117
// source=swiftui/Sources/Lemonade/LemonadeIcons.swift
// component=LemonadeIcon
import figma from 'figma'

export default {
  example: figma.swift`LemonadeIcon.mathTimes`,
  id: 'icon-math-times',
  metadata: { nestable: true },
}
