// DO NOT MODIFY THIS FILE MANUALLY — generated by scripts/generate-asset-templates.mjs
// url=<LEMONADE_ICONS>?node-id=3245-150
// source=swiftui/Sources/Lemonade/LemonadeIcons.swift
// component=LemonadeIcon
import figma from 'figma'

export default {
  example: figma.swift`LemonadeIcon.moneyBag`,
  id: 'icon-money-bag',
  metadata: { nestable: true },
}
