// DO NOT MODIFY THIS FILE MANUALLY — generated by scripts/generate-asset-templates.mjs
// url=<LEMONADE_ICONS>?node-id=3487-284
// source=swiftui/Sources/Lemonade/LemonadeIcons.swift
// component=LemonadeIcon
import figma from 'figma'

export default {
  example: figma.swift`LemonadeIcon.sparklesSoftSolid`,
  id: 'icon-sparkles-soft-solid',
  metadata: { nestable: true },
}
