// DO NOT MODIFY THIS FILE MANUALLY — generated by scripts/generate-asset-templates.mjs
// url=<LEMONADE_FLAGS>?node-id=1493-15624
// source=kmp/core/src/commonMain/kotlin/com/teya/lemonade/core/LemonadeCountryFlags.kt
// component=LemonadeCountryFlags
import figma from 'figma'

export default {
  example: figma.kotlin`LemonadeCountryFlags.AFAfghanistan`,
  imports: ['import com.teya.lemonade.core.LemonadeCountryFlags'],
  id: 'flag-AF-afghanistan',
  metadata: { nestable: true },
}
