// DO NOT MODIFY THIS FILE MANUALLY — generated by scripts/generate-asset-templates.mjs
// url=<LEMONADE_FLAGS>?node-id=1493-15594
// source=kmp/core/src/commonMain/kotlin/com/teya/lemonade/core/LemonadeCountryFlags.kt
// component=LemonadeCountryFlags
import figma from 'figma'

export default {
  example: figma.kotlin`LemonadeCountryFlags.SISlovenia`,
  imports: ['import com.teya.lemonade.core.LemonadeCountryFlags'],
  id: 'flag-SI-slovenia',
  metadata: { nestable: true },
}
