// DO NOT MODIFY THIS FILE MANUALLY — generated by scripts/generate-asset-templates.mjs
// url=<LEMONADE_FLAGS>?node-id=1493-15587
// source=kmp/core/src/commonMain/kotlin/com/teya/lemonade/core/LemonadeCountryFlags.kt
// component=LemonadeCountryFlags
import figma from 'figma'

export default {
  example: figma.kotlin`LemonadeCountryFlags.SVElSalvador`,
  imports: ['import com.teya.lemonade.core.LemonadeCountryFlags'],
  id: 'flag-SV-el-salvador',
  metadata: { nestable: true },
}
