package com.teya.lemonade.core

/**
 * Auto-generated enum class containing all brandLogos converted from SVG files.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the svg-asset-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add new brandLogos:
 * 1. Add your SVG file to the svg/brandLogos/ directory
 * 2. Run: kotlin scripts/svg-asset-converter.main.kts
 *
 * @generated by svg-asset-converter.main.kts
 */
public enum class LemonadeBrandLogos : LemonadeAsset {
    Amazon,
    Amex,
    ApplePay,
    Bancomat,
    CartesBancaires,
    Diners,
    DirectDebit,
    Discover,
    Edenred,
    GenericMealOrHealthIssuer,
    Girocard,
    GooglePay,
    Jcb,
    Maestro,
    Mastercard,
    MbWay,
    Multibanco,
    NfcLogo,
    PagoBancomat,
    Paypal,
    Pluxee,
    Sepa,
    Sodexo,
    Unionpay,
    Visa,
}
