package com.teya.lemonade

import androidx.compose.runtime.Stable

/**
 * Dark implementation of the themed colour palette.
 * See [LemonadeThemedColors] for details on the colour structure.
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-themed-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-themed-token-converter.main.kts
 *
 * @generated by scripts/kmp-themed-token-converter.main.kts
 */
@Stable
public object LemonadeDarkThemedColors : LemonadeThemedColors {
    override val amber: LemonadeThemedColors.AmberColors =
        object : LemonadeThemedColors.AmberColors {
            override val background = LemonadePrimitiveColors.Solid.Amber.amber400
            override val backgroundSubtle = LemonadePrimitiveColors.Alpha.Amber.alpha100
            override val border = LemonadePrimitiveColors.Solid.Amber.amber400
            override val borderSubtle = LemonadePrimitiveColors.Alpha.Amber.alpha100
            override val content = LemonadePrimitiveColors.Solid.Amber.amber400
            override val contentOnColor = LemonadePrimitiveColors.Solid.Amber.amber700
            override val onBackground = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        }

    override val blue: LemonadeThemedColors.BlueColors =
        object : LemonadeThemedColors.BlueColors {
            override val background = LemonadePrimitiveColors.Solid.Blue.blue400
            override val backgroundSubtle = LemonadePrimitiveColors.Alpha.Blue.alpha100
            override val border = LemonadePrimitiveColors.Solid.Blue.blue400
            override val borderSubtle = LemonadePrimitiveColors.Alpha.Blue.alpha100
            override val content = LemonadePrimitiveColors.Solid.Blue.blue400
            override val contentOnColor = LemonadePrimitiveColors.Solid.Blue.blue700
            override val onBackground = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        }

    override val cyan: LemonadeThemedColors.CyanColors =
        object : LemonadeThemedColors.CyanColors {
            override val background = LemonadePrimitiveColors.Solid.Cyan.cyan400
            override val backgroundSubtle = LemonadePrimitiveColors.Alpha.Cyan.alpha100
            override val border = LemonadePrimitiveColors.Solid.Cyan.cyan400
            override val borderSubtle = LemonadePrimitiveColors.Alpha.Cyan.alpha100
            override val content = LemonadePrimitiveColors.Solid.Cyan.cyan400
            override val contentOnColor = LemonadePrimitiveColors.Solid.Cyan.cyan700
            override val onBackground = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        }

    override val fuchsia: LemonadeThemedColors.FuchsiaColors =
        object : LemonadeThemedColors.FuchsiaColors {
            override val background = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia400
            override val backgroundSubtle = LemonadePrimitiveColors.Alpha.Fuchsia.alpha100
            override val border = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia400
            override val borderSubtle = LemonadePrimitiveColors.Alpha.Fuchsia.alpha100
            override val content = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia400
            override val contentOnColor = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia700
            override val onBackground = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        }

    override val green: LemonadeThemedColors.GreenColors =
        object : LemonadeThemedColors.GreenColors {
            override val background = LemonadePrimitiveColors.Solid.Green.green400
            override val backgroundSubtle = LemonadePrimitiveColors.Alpha.Green.alpha100
            override val border = LemonadePrimitiveColors.Solid.Green.green400
            override val borderSubtle = LemonadePrimitiveColors.Alpha.Green.alpha100
            override val content = LemonadePrimitiveColors.Solid.Green.green400
            override val contentOnColor = LemonadePrimitiveColors.Solid.Green.green700
            override val onBackground = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        }

    override val greenLime: LemonadeThemedColors.GreenLimeColors =
        object : LemonadeThemedColors.GreenLimeColors {
            override val background = LemonadePrimitiveColors.Solid.GreenLime.greenLime400
            override val backgroundSubtle = LemonadePrimitiveColors.Alpha.GreenLime.alpha100
            override val border = LemonadePrimitiveColors.Solid.GreenLime.greenLime400
            override val borderSubtle = LemonadePrimitiveColors.Alpha.GreenLime.alpha100
            override val content = LemonadePrimitiveColors.Solid.GreenLime.greenLime400
            override val contentOnColor = LemonadePrimitiveColors.Solid.GreenLime.greenLime700
            override val onBackground = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        }

    override val indigo: LemonadeThemedColors.IndigoColors =
        object : LemonadeThemedColors.IndigoColors {
            override val background = LemonadePrimitiveColors.Solid.Indigo.indigo400
            override val backgroundSubtle = LemonadePrimitiveColors.Alpha.Indigo.alpha100
            override val border = LemonadePrimitiveColors.Solid.Indigo.indigo400
            override val borderSubtle = LemonadePrimitiveColors.Alpha.Indigo.alpha100
            override val content = LemonadePrimitiveColors.Solid.Indigo.indigo400
            override val contentOnColor = LemonadePrimitiveColors.Solid.Indigo.indigo700
            override val onBackground = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        }

    override val neutral: LemonadeThemedColors.NeutralColors =
        object : LemonadeThemedColors.NeutralColors {
            override val background = LemonadePrimitiveColors.Solid.Neutral.neutral400
            override val backgroundSubtle = LemonadePrimitiveColors.Solid.White.white100
            override val border = LemonadePrimitiveColors.Solid.Neutral.neutral400
            override val borderSubtle = LemonadePrimitiveColors.Solid.White.white100
            override val content = LemonadePrimitiveColors.Solid.White.white900
            override val contentOnColor = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val onBackground = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        }

    override val orange: LemonadeThemedColors.OrangeColors =
        object : LemonadeThemedColors.OrangeColors {
            override val background = LemonadePrimitiveColors.Solid.Orange.orange400
            override val backgroundSubtle = LemonadePrimitiveColors.Alpha.Orange.alpha100
            override val border = LemonadePrimitiveColors.Solid.Orange.orange400
            override val borderSubtle = LemonadePrimitiveColors.Alpha.Orange.alpha100
            override val content = LemonadePrimitiveColors.Solid.Orange.orange400
            override val contentOnColor = LemonadePrimitiveColors.Solid.Orange.orange700
            override val onBackground = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        }

    override val pink: LemonadeThemedColors.PinkColors =
        object : LemonadeThemedColors.PinkColors {
            override val background = LemonadePrimitiveColors.Solid.Pink.pink400
            override val backgroundSubtle = LemonadePrimitiveColors.Alpha.Pink.alpha100
            override val border = LemonadePrimitiveColors.Solid.Pink.pink400
            override val borderSubtle = LemonadePrimitiveColors.Alpha.Pink.alpha100
            override val content = LemonadePrimitiveColors.Solid.Pink.pink400
            override val contentOnColor = LemonadePrimitiveColors.Solid.Pink.pink700
            override val onBackground = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        }

    override val purple: LemonadeThemedColors.PurpleColors =
        object : LemonadeThemedColors.PurpleColors {
            override val background = LemonadePrimitiveColors.Solid.Purple.purple400
            override val backgroundSubtle = LemonadePrimitiveColors.Alpha.Purple.alpha100
            override val border = LemonadePrimitiveColors.Solid.Purple.purple400
            override val borderSubtle = LemonadePrimitiveColors.Alpha.Purple.alpha100
            override val content = LemonadePrimitiveColors.Solid.Purple.purple400
            override val contentOnColor = LemonadePrimitiveColors.Solid.Purple.purple700
            override val onBackground = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        }

    override val red: LemonadeThemedColors.RedColors =
        object : LemonadeThemedColors.RedColors {
            override val background = LemonadePrimitiveColors.Solid.Red.red400
            override val backgroundSubtle = LemonadePrimitiveColors.Alpha.Red.alpha100
            override val border = LemonadePrimitiveColors.Solid.Red.red400
            override val borderSubtle = LemonadePrimitiveColors.Alpha.Red.alpha100
            override val content = LemonadePrimitiveColors.Solid.Red.red400
            override val contentOnColor = LemonadePrimitiveColors.Solid.Red.red700
            override val onBackground = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        }

    override val rose: LemonadeThemedColors.RoseColors =
        object : LemonadeThemedColors.RoseColors {
            override val background = LemonadePrimitiveColors.Solid.Rose.rose400
            override val backgroundSubtle = LemonadePrimitiveColors.Alpha.Rose.alpha100
            override val border = LemonadePrimitiveColors.Solid.Rose.rose400
            override val borderSubtle = LemonadePrimitiveColors.Alpha.Rose.alpha100
            override val content = LemonadePrimitiveColors.Solid.Rose.rose400
            override val contentOnColor = LemonadePrimitiveColors.Solid.Rose.rose700
            override val onBackground = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        }

    override val teal: LemonadeThemedColors.TealColors =
        object : LemonadeThemedColors.TealColors {
            override val background = LemonadePrimitiveColors.Solid.Teal.teal400
            override val backgroundSubtle = LemonadePrimitiveColors.Alpha.Teal.alpha100
            override val border = LemonadePrimitiveColors.Solid.Teal.teal400
            override val borderSubtle = LemonadePrimitiveColors.Alpha.Teal.alpha100
            override val content = LemonadePrimitiveColors.Solid.Teal.teal400
            override val contentOnColor = LemonadePrimitiveColors.Solid.Teal.teal700
            override val onBackground = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        }

    override val violet: LemonadeThemedColors.VioletColors =
        object : LemonadeThemedColors.VioletColors {
            override val background = LemonadePrimitiveColors.Solid.Violet.violet400
            override val backgroundSubtle = LemonadePrimitiveColors.Alpha.Violet.alpha100
            override val border = LemonadePrimitiveColors.Solid.Violet.violet400
            override val borderSubtle = LemonadePrimitiveColors.Alpha.Violet.alpha100
            override val content = LemonadePrimitiveColors.Solid.Violet.violet400
            override val contentOnColor = LemonadePrimitiveColors.Solid.Violet.violet700
            override val onBackground = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        }

    override val yellow: LemonadeThemedColors.YellowColors =
        object : LemonadeThemedColors.YellowColors {
            override val background = LemonadePrimitiveColors.Solid.Yellow.yellow400
            override val backgroundSubtle = LemonadePrimitiveColors.Alpha.Yellow.alpha100
            override val border = LemonadePrimitiveColors.Solid.Yellow.yellow400
            override val borderSubtle = LemonadePrimitiveColors.Alpha.Yellow.alpha100
            override val content = LemonadePrimitiveColors.Solid.Yellow.yellow400
            override val contentOnColor = LemonadePrimitiveColors.Solid.Yellow.yellow700
            override val onBackground = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        }

    override val yellowLime: LemonadeThemedColors.YellowLimeColors =
        object : LemonadeThemedColors.YellowLimeColors {
            override val background = LemonadePrimitiveColors.Solid.YellowLime.yellowLime400
            override val backgroundSubtle = LemonadePrimitiveColors.Alpha.YellowLime.alpha100
            override val border = LemonadePrimitiveColors.Solid.YellowLime.yellowLime400
            override val borderSubtle = LemonadePrimitiveColors.Alpha.YellowLime.alpha100
            override val content = LemonadePrimitiveColors.Solid.YellowLime.yellowLime400
            override val contentOnColor = LemonadePrimitiveColors.Solid.YellowLime.yellowLime700
            override val onBackground = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        }
}
