package com.teya.lemonade

import androidx.compose.runtime.Stable

/**
 * Dark implementation of the themed colour palette.
 * See [LemonadeThemedColors] for details on the colour structure.
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-themed-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-themed-token-converter.main.kts
 *
 * @generated by scripts/kmp-themed-token-converter.main.kts
 */
@Stable
public object LemonadeDarkThemedColors : LemonadeThemedColors {
    override val background: LemonadeThemedColors.BackgroundColors =
        object : LemonadeThemedColors.BackgroundColors {
            override val bgAmber = LemonadePrimitiveColors.Solid.Amber.amber400
            override val bgAmberSubtle = LemonadePrimitiveColors.Alpha.Amber.alpha100
            override val bgBlue = LemonadePrimitiveColors.Solid.Blue.blue400
            override val bgBlueSubtle = LemonadePrimitiveColors.Alpha.Blue.alpha100
            override val bgCyan = LemonadePrimitiveColors.Solid.Cyan.cyan400
            override val bgCyanSubtle = LemonadePrimitiveColors.Alpha.Cyan.alpha100
            override val bgFuchsia = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia400
            override val bgFuchsiaSubtle = LemonadePrimitiveColors.Alpha.Fuchsia.alpha100
            override val bgGreen = LemonadePrimitiveColors.Solid.Green.green400
            override val bgGreenLime = LemonadePrimitiveColors.Solid.GreenLime.greenLime400
            override val bgGreenLimeSubtle = LemonadePrimitiveColors.Alpha.GreenLime.alpha100
            override val bgGreenSubtle = LemonadePrimitiveColors.Alpha.Green.alpha100
            override val bgIndigo = LemonadePrimitiveColors.Solid.Indigo.indigo400
            override val bgIndigoSubtle = LemonadePrimitiveColors.Alpha.Indigo.alpha100
            override val bgOrange = LemonadePrimitiveColors.Solid.Orange.orange400
            override val bgOrangeSubtle = LemonadePrimitiveColors.Alpha.Orange.alpha100
            override val bgPink = LemonadePrimitiveColors.Solid.Pink.pink400
            override val bgPinkSubtle = LemonadePrimitiveColors.Alpha.Pink.alpha100
            override val bgPurple = LemonadePrimitiveColors.Solid.Purple.purple400
            override val bgPurpleSubtle = LemonadePrimitiveColors.Alpha.Purple.alpha100
            override val bgRed = LemonadePrimitiveColors.Solid.Red.red400
            override val bgRedSubtle = LemonadePrimitiveColors.Alpha.Red.alpha100
            override val bgRose = LemonadePrimitiveColors.Solid.Rose.rose400
            override val bgRoseSubtle = LemonadePrimitiveColors.Alpha.Rose.alpha100
            override val bgTeal = LemonadePrimitiveColors.Solid.Teal.teal400
            override val bgTealSubtle = LemonadePrimitiveColors.Alpha.Teal.alpha100
            override val bgViolet = LemonadePrimitiveColors.Solid.Violet.violet400
            override val bgVioletSubtle = LemonadePrimitiveColors.Alpha.Violet.alpha100
            override val bgYellow = LemonadePrimitiveColors.Solid.Yellow.yellow400
            override val bgYellowLime = LemonadePrimitiveColors.Solid.YellowLime.yellowLime400
            override val bgYellowLimeSubtle = LemonadePrimitiveColors.Alpha.YellowLime.alpha100
            override val bgYellowSubtle = LemonadePrimitiveColors.Alpha.Yellow.alpha100
        }

    override val border: LemonadeThemedColors.BorderColors =
        object : LemonadeThemedColors.BorderColors {
            override val borderAmber = LemonadePrimitiveColors.Solid.Amber.amber400
            override val borderAmberSubtle = LemonadePrimitiveColors.Alpha.Amber.alpha100
            override val borderBlue = LemonadePrimitiveColors.Solid.Blue.blue400
            override val borderBlueSubtle = LemonadePrimitiveColors.Alpha.Blue.alpha100
            override val borderCyan = LemonadePrimitiveColors.Solid.Cyan.cyan400
            override val borderCyanSubtle = LemonadePrimitiveColors.Alpha.Cyan.alpha100
            override val borderFuchsia = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia400
            override val borderFuchsiaSubtle = LemonadePrimitiveColors.Alpha.Fuchsia.alpha100
            override val borderGreen = LemonadePrimitiveColors.Solid.Green.green400
            override val borderGreenLime = LemonadePrimitiveColors.Solid.GreenLime.greenLime400
            override val borderGreenLimeSubtle = LemonadePrimitiveColors.Alpha.GreenLime.alpha100
            override val borderGreenSubtle = LemonadePrimitiveColors.Alpha.Green.alpha100
            override val borderIndigo = LemonadePrimitiveColors.Solid.Indigo.indigo400
            override val borderIndigoSubtle = LemonadePrimitiveColors.Alpha.Indigo.alpha100
            override val borderOrange = LemonadePrimitiveColors.Solid.Orange.orange400
            override val borderOrangeSubtle = LemonadePrimitiveColors.Alpha.Orange.alpha100
            override val borderPink = LemonadePrimitiveColors.Solid.Pink.pink400
            override val borderPinkSubtle = LemonadePrimitiveColors.Alpha.Pink.alpha100
            override val borderPurple = LemonadePrimitiveColors.Solid.Purple.purple400
            override val borderPurpleSubtle = LemonadePrimitiveColors.Alpha.Purple.alpha100
            override val borderRed = LemonadePrimitiveColors.Solid.Red.red400
            override val borderRedSubtle = LemonadePrimitiveColors.Alpha.Red.alpha100
            override val borderRose = LemonadePrimitiveColors.Solid.Rose.rose400
            override val borderRoseSubtle = LemonadePrimitiveColors.Alpha.Rose.alpha100
            override val borderTeal = LemonadePrimitiveColors.Solid.Teal.teal400
            override val borderTealSubtle = LemonadePrimitiveColors.Alpha.Teal.alpha100
            override val borderViolet = LemonadePrimitiveColors.Solid.Violet.violet400
            override val borderVioletSubtle = LemonadePrimitiveColors.Alpha.Violet.alpha100
            override val borderYellow = LemonadePrimitiveColors.Solid.Yellow.yellow400
            override val borderYellowLime = LemonadePrimitiveColors.Solid.YellowLime.yellowLime400
            override val borderYellowLimeSubtle = LemonadePrimitiveColors.Alpha.YellowLime.alpha100
            override val borderYellowSubtle = LemonadePrimitiveColors.Alpha.Yellow.alpha100
        }

    override val content: LemonadeThemedColors.ContentColors =
        object : LemonadeThemedColors.ContentColors {
            override val contentAmber = LemonadePrimitiveColors.Solid.Amber.amber400
            override val contentAmberOnColor = LemonadePrimitiveColors.Solid.Amber.amber700
            override val contentBlue = LemonadePrimitiveColors.Solid.Blue.blue400
            override val contentBlueOnColor = LemonadePrimitiveColors.Solid.Blue.blue700
            override val contentCyan = LemonadePrimitiveColors.Solid.Cyan.cyan400
            override val contentCyanOnColor = LemonadePrimitiveColors.Solid.Cyan.cyan700
            override val contentFuchsia = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia400
            override val contentFuchsiaOnColor = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia700
            override val contentGreen = LemonadePrimitiveColors.Solid.Green.green400
            override val contentGreenLime = LemonadePrimitiveColors.Solid.GreenLime.greenLime400
            override val contentGreenLimeOnColor = LemonadePrimitiveColors.Solid.GreenLime.greenLime700
            override val contentGreenOnColor = LemonadePrimitiveColors.Solid.Green.green700
            override val contentIndigo = LemonadePrimitiveColors.Solid.Indigo.indigo400
            override val contentIndigoOnColor = LemonadePrimitiveColors.Solid.Indigo.indigo700
            override val contentOnAmber = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentOnBlue = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentOnCyan = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentOnFuchsia = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentOnGreen = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentOnGreenLime = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentOnIndigo = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentOnOrange = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentOnPink = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentOnPurple = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentOnRed = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentOnRose = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentOnTeal = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentOnViolet = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentOnYellow = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentOnYellowLime = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentOrange = LemonadePrimitiveColors.Solid.Orange.orange400
            override val contentOrangeOnColor = LemonadePrimitiveColors.Solid.Orange.orange700
            override val contentPink = LemonadePrimitiveColors.Solid.Pink.pink400
            override val contentPinkOnColor = LemonadePrimitiveColors.Solid.Pink.pink700
            override val contentPurple = LemonadePrimitiveColors.Solid.Purple.purple400
            override val contentPurpleOnColor = LemonadePrimitiveColors.Solid.Purple.purple700
            override val contentRed = LemonadePrimitiveColors.Solid.Red.red400
            override val contentRedOnColor = LemonadePrimitiveColors.Solid.Red.red700
            override val contentRose = LemonadePrimitiveColors.Solid.Rose.rose400
            override val contentRoseOnColor = LemonadePrimitiveColors.Solid.Rose.rose700
            override val contentTeal = LemonadePrimitiveColors.Solid.Teal.teal400
            override val contentTealOnColor = LemonadePrimitiveColors.Solid.Teal.teal700
            override val contentViolet = LemonadePrimitiveColors.Solid.Violet.violet400
            override val contentVioletOnColor = LemonadePrimitiveColors.Solid.Violet.violet700
            override val contentYellow = LemonadePrimitiveColors.Solid.Yellow.yellow400
            override val contentYellowLime = LemonadePrimitiveColors.Solid.YellowLime.yellowLime400
            override val contentYellowLimeOnColor = LemonadePrimitiveColors.Solid.YellowLime.yellowLime700
            override val contentYellowOnColor = LemonadePrimitiveColors.Solid.Yellow.yellow700
        }
}
