package com.teya.lemonade

import androidx.compose.runtime.Stable

/**
 * Light theme implementation of semantic colors
 * See [LemonadeSemanticColors] for details on the color structure.
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-theme-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-theme-token-converter.main.kts
 *
 * @generated by scripts/kmp-theme-token-converter.main.kts
 */
@Stable
@OptIn(InternalLemonadeApi::class)
public object LemonadeLightTheme : LemonadeSemanticColors {
    override val isDark: Boolean = false

    override val background: LemonadeSemanticColors.BackgroundColors =
        object : LemonadeSemanticColors.BackgroundColors {
            override val bgBrand = LemonadePrimitiveColors.Solid.YellowLime.yellowLime500
            override val bgBrandElevated = LemonadePrimitiveColors.Solid.White.white500
            override val bgBrandHigh = LemonadePrimitiveColors.Solid.YellowLime.yellowLime800
            override val bgBrandSubtle = LemonadePrimitiveColors.Alpha.YellowLime.alpha300
            override val bgAlwaysDark = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val bgAlwaysDarkHigh = LemonadePrimitiveColors.Alpha.Neutral.alpha300
            override val bgAlwaysDarkLow = LemonadePrimitiveColors.Alpha.Neutral.alpha50
            override val bgAlwaysDarkMedium = LemonadePrimitiveColors.Alpha.Neutral.alpha200
            override val bgAlwaysLight = LemonadePrimitiveColors.Solid.White.white950
            override val bgAlwaysLightHigh = LemonadePrimitiveColors.Solid.White.white200
            override val bgAlwaysLightLow = LemonadePrimitiveColors.Solid.White.white50
            override val bgAlwaysLightMedium = LemonadePrimitiveColors.Solid.White.white100
            override val bgDefaultInverse = LemonadePrimitiveColors.Solid.Neutral.neutral950
            override val bgElevatedInverse = LemonadePrimitiveColors.Solid.White.white100
            override val bgSubtleInverse = LemonadePrimitiveColors.Solid.Neutral.neutral900
            override val bgCaution = LemonadePrimitiveColors.Solid.Amber.amber600
            override val bgCautionSubtle = LemonadePrimitiveColors.Alpha.Amber.alpha100
            override val bgCritical = LemonadePrimitiveColors.Solid.Red.red500
            override val bgCriticalSubtle = LemonadePrimitiveColors.Alpha.Red.alpha100
            override val bgFeatured = LemonadePrimitiveColors.Solid.Purple.purple600
            override val bgFeaturedSubtle = LemonadePrimitiveColors.Alpha.Purple.alpha100
            override val bgInfo = LemonadePrimitiveColors.Solid.Blue.blue600
            override val bgInfoSubtle = LemonadePrimitiveColors.Alpha.Blue.alpha100
            override val bgNeutral = LemonadePrimitiveColors.Solid.Neutral.neutral600
            override val bgNeutralSubtle = LemonadePrimitiveColors.Alpha.Neutral.alpha100
            override val bgPositive = LemonadePrimitiveColors.Solid.GreenLime.greenLime600
            override val bgPositiveSubtle = LemonadePrimitiveColors.Alpha.GreenLime.alpha100
            override val bgDefault = LemonadePrimitiveColors.Solid.White.white950
            override val bgElevated = LemonadePrimitiveColors.Alpha.Neutral.alpha50
            override val bgElevatedHigh = LemonadePrimitiveColors.Alpha.Neutral.alpha200
            override val bgSubtle = LemonadePrimitiveColors.Solid.Neutral.neutral50
        }
    override val border: LemonadeSemanticColors.BorderColors =
        object : LemonadeSemanticColors.BorderColors {
            override val borderBrand = LemonadePrimitiveColors.Solid.YellowLime.yellowLime600
            override val borderOnBrandHigh = LemonadePrimitiveColors.Solid.White.white700
            override val borderOnBrandLow = LemonadePrimitiveColors.Solid.White.white300
            override val borderOnBrandMedium = LemonadePrimitiveColors.Solid.White.white500
            override val borderAlwaysDark = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val borderAlwaysDarkHigh = LemonadePrimitiveColors.Alpha.Neutral.alpha300
            override val borderAlwaysDarkLow = LemonadePrimitiveColors.Alpha.Neutral.alpha100
            override val borderAlwaysDarkMedium = LemonadePrimitiveColors.Alpha.Neutral.alpha200
            override val borderAlwaysLight = LemonadePrimitiveColors.Solid.White.white950
            override val borderAlwaysLightHigh = LemonadePrimitiveColors.Solid.White.white500
            override val borderAlwaysLightLow = LemonadePrimitiveColors.Solid.White.white100
            override val borderAlwaysLightMedium = LemonadePrimitiveColors.Solid.White.white300
            override val borderBrandInverse = LemonadePrimitiveColors.Solid.YellowLime.yellowLime600
            override val borderNeutralHighInverse = LemonadePrimitiveColors.Solid.White.white400
            override val borderNeutralLowInverse = LemonadePrimitiveColors.Solid.White.white200
            override val borderNeutralMediumInverse = LemonadePrimitiveColors.Solid.White.white300
            override val borderSelectedInverse = LemonadePrimitiveColors.Solid.YellowLime.yellowLime500
            override val borderCaution = LemonadePrimitiveColors.Solid.Amber.amber600
            override val borderCautionSubtle = LemonadePrimitiveColors.Alpha.Orange.alpha100
            override val borderCritical = LemonadePrimitiveColors.Solid.Red.red600
            override val borderCriticalSubtle = LemonadePrimitiveColors.Alpha.Red.alpha100
            override val borderFeatured = LemonadePrimitiveColors.Solid.Purple.purple600
            override val borderFeaturedSubtle = LemonadePrimitiveColors.Alpha.Purple.alpha100
            override val borderInfo = LemonadePrimitiveColors.Solid.Blue.blue600
            override val borderInfoSubtle = LemonadePrimitiveColors.Alpha.Blue.alpha100
            override val borderPositive = LemonadePrimitiveColors.Solid.GreenLime.greenLime600
            override val borderPositiveSubtle = LemonadePrimitiveColors.Alpha.GreenLime.alpha100
            override val borderNeutralHigh = LemonadePrimitiveColors.Alpha.Neutral.alpha300
            override val borderNeutralLow = LemonadePrimitiveColors.Alpha.Neutral.alpha100
            override val borderNeutralMedium = LemonadePrimitiveColors.Alpha.Neutral.alpha200
            override val borderSelected = LemonadePrimitiveColors.Solid.YellowLime.yellowLime900
        }
    override val content: LemonadeSemanticColors.ContentColors =
        object : LemonadeSemanticColors.ContentColors {
            override val contentBrand = LemonadePrimitiveColors.Solid.YellowLime.yellowLime700
            override val contentBrandHigh = LemonadePrimitiveColors.Solid.YellowLime.yellowLime900
            override val contentOnBrandHigh = LemonadePrimitiveColors.Solid.YellowLime.yellowLime900
            override val contentOnBrandLow = LemonadePrimitiveColors.Solid.YellowLime.yellowLime700
            override val contentAlwaysDark = LemonadePrimitiveColors.Alpha.Neutral.alpha950
            override val contentAlwaysLight = LemonadePrimitiveColors.Solid.White.white950
            override val contentCautionAlwaysOnColor = LemonadePrimitiveColors.Solid.Amber.amber400
            override val contentCriticalAlwaysOnColor = LemonadePrimitiveColors.Solid.Red.red400
            override val contentInfoAlwaysOnColor = LemonadePrimitiveColors.Solid.Blue.blue400
            override val contentNeutralAlwaysOnColor = LemonadePrimitiveColors.Solid.White.white900
            override val contentPositiveAlwaysOnColor = LemonadePrimitiveColors.Solid.GreenLime.greenLime400
            override val contentBrandInverse = LemonadePrimitiveColors.Solid.YellowLime.yellowLime500
            override val contentPrimaryInverse = LemonadePrimitiveColors.Solid.White.white950
            override val contentSecondaryInverse = LemonadePrimitiveColors.Solid.White.white800
            override val contentTertiaryInverse = LemonadePrimitiveColors.Solid.White.white700
            override val contentCautionOnColor = LemonadePrimitiveColors.Solid.Amber.amber400
            override val contentCriticalOnColor = LemonadePrimitiveColors.Solid.Red.red400
            override val contentFeaturedOnColor = LemonadePrimitiveColors.Solid.Purple.purple400
            override val contentInfoOnColor = LemonadePrimitiveColors.Solid.Blue.blue400
            override val contentNeutralOnColor = LemonadePrimitiveColors.Solid.White.white800
            override val contentPositiveOnColor = LemonadePrimitiveColors.Solid.GreenLime.greenLime400
            override val contentCaution = LemonadePrimitiveColors.Solid.Amber.amber700
            override val contentCritical = LemonadePrimitiveColors.Solid.Red.red600
            override val contentFeatured = LemonadePrimitiveColors.Solid.Purple.purple700
            override val contentInfo = LemonadePrimitiveColors.Solid.Blue.blue700
            override val contentNeutral = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentPositive = LemonadePrimitiveColors.Solid.GreenLime.greenLime700
            override val contentPrimary = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentSecondary = LemonadePrimitiveColors.Alpha.Neutral.alpha500
            override val contentTertiary = LemonadePrimitiveColors.Alpha.Neutral.alpha400
        }
    override val interaction: LemonadeSemanticColors.InteractionColors =
        object : LemonadeSemanticColors.InteractionColors {
            override val bgAlwaysDarkHighInteractive = LemonadePrimitiveColors.Alpha.Neutral.alpha400
            override val bgAlwaysDarkLowInteractive = LemonadePrimitiveColors.Alpha.Neutral.alpha100
            override val bgAlwaysDarkMediumInteractive = LemonadePrimitiveColors.Alpha.Neutral.alpha300
            override val bgAlwaysLightHighInteractive = LemonadePrimitiveColors.Solid.White.white300
            override val bgAlwaysLightLowInteractive = LemonadePrimitiveColors.Solid.White.white100
            override val bgAlwaysLightMediumInteractive = LemonadePrimitiveColors.Solid.White.white200
            override val bgBrandElevatedInteractive = LemonadePrimitiveColors.Solid.White.white600
            override val bgBrandHighInteractive = LemonadePrimitiveColors.Solid.YellowLime.yellowLime900
            override val bgBrandInteractive = LemonadePrimitiveColors.Solid.YellowLime.yellowLime400
            override val bgCautionInteractive = LemonadePrimitiveColors.Solid.Orange.orange500
            override val bgCautionSubtleInteractive = LemonadePrimitiveColors.Alpha.Orange.alpha200
            override val bgCriticalInteractive = LemonadePrimitiveColors.Solid.Red.red500
            override val bgCriticalSubtleInteractive = LemonadePrimitiveColors.Alpha.Red.alpha200
            override val bgDefaultInteractive = LemonadePrimitiveColors.Solid.Neutral.neutral50
            override val bgElevatedHighInteractive = LemonadePrimitiveColors.Alpha.Neutral.alpha300
            override val bgElevatedInteractive = LemonadePrimitiveColors.Alpha.Neutral.alpha200
            override val bgFeaturedInteractive = LemonadePrimitiveColors.Solid.Purple.purple500
            override val bgFeaturedSubtleInteractive = LemonadePrimitiveColors.Alpha.Purple.alpha200
            override val bgInfoInteractive = LemonadePrimitiveColors.Solid.Blue.blue500
            override val bgInfoSubtleInteractive = LemonadePrimitiveColors.Alpha.Blue.alpha200
            override val bgNeutralInteractive = LemonadePrimitiveColors.Solid.Neutral.neutral700
            override val bgNeutralSubtleInteractive = LemonadePrimitiveColors.Solid.Black.black200
            override val bgPositiveInteractive = LemonadePrimitiveColors.Solid.GreenLime.greenLime500
            override val bgPositiveSubtleInteractive = LemonadePrimitiveColors.Alpha.GreenLime.alpha200
            override val bgSubtleInteractive = LemonadePrimitiveColors.Alpha.Neutral.alpha100
            override val bgBrandElevatedPressed = LemonadePrimitiveColors.Solid.White.white600
            override val bgBrandHighPressed = LemonadePrimitiveColors.Solid.YellowLime.yellowLime950
            override val bgBrandPressed = LemonadePrimitiveColors.Solid.YellowLime.yellowLime600
            override val bgCautionPressed = LemonadePrimitiveColors.Solid.Amber.amber700
            override val bgCautionSubtlePressed = LemonadePrimitiveColors.Alpha.Amber.alpha300
            override val bgCriticalPressed = LemonadePrimitiveColors.Solid.Red.red700
            override val bgCriticalSubtlePressed = LemonadePrimitiveColors.Alpha.Red.alpha300
            override val bgDefaultPressed = LemonadePrimitiveColors.Alpha.Neutral.alpha100
            override val bgElevatedPressed = LemonadePrimitiveColors.Alpha.Neutral.alpha300
            override val bgFeaturedPressed = LemonadePrimitiveColors.Solid.Purple.purple700
            override val bgFeaturedSubtlePressed = LemonadePrimitiveColors.Alpha.Purple.alpha300
            override val bgInfoPressed = LemonadePrimitiveColors.Solid.Blue.blue700
            override val bgInfoSubtlePressed = LemonadePrimitiveColors.Alpha.Blue.alpha300
            override val bgNeutralPressed = LemonadePrimitiveColors.Solid.Neutral.neutral800
            override val bgNeutralSubtlePressed = LemonadePrimitiveColors.Solid.Black.black300
            override val bgPositivePressed = LemonadePrimitiveColors.Solid.Green.green600
            override val bgPositiveSubtlePressed = LemonadePrimitiveColors.Alpha.GreenLime.alpha300
            override val bgSubtlePressed = LemonadePrimitiveColors.Alpha.Neutral.alpha200
        }
    override val scoped: LemonadeSemanticColors.ScopedColors =
        object : LemonadeSemanticColors.ScopedColors {
            override val bgSettlementBusinessDays = LemonadePrimitiveColors.Solid.Blue.blue200
            override val bgSettlementEveryday = LemonadePrimitiveColors.Solid.Violet.violet200
            override val bgSettlementInstant = LemonadePrimitiveColors.Solid.YellowLime.yellowLime500
            override val bgSettlementScheduled = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia200
            override val contentOnSettlementBusinessDays = LemonadePrimitiveColors.Solid.Blue.blue800
            override val contentOnSettlementEveryday = LemonadePrimitiveColors.Solid.Violet.violet800
            override val contentOnSettlementInstant = LemonadePrimitiveColors.Solid.YellowLime.yellowLime900
            override val contentOnSettlementScheduled = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia800
        }
    override val shadow: LemonadeSemanticColors.ShadowColors =
        object : LemonadeSemanticColors.ShadowColors {
            override val shadowDefault = LemonadePrimitiveColors.Solid.Black.black50
        }
}
