package com.teya.lemonade

import androidx.compose.runtime.Stable

/**
 * Dark implementation of the themed colour palette.
 * See [LemonadeThemedColors] for details on the colour structure.
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-themed-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-themed-token-converter.main.kts
 *
 * @generated by scripts/kmp-themed-token-converter.main.kts
 */
@Stable
@ExperimentalLemonadeApi
public object LemonadeDarkThemedColors : LemonadeThemedColors {
    override val amber: ThemedPrimaryColor =
        object : ThemedPrimaryColor {
            override val background = LemonadePrimitiveColors.Solid.Amber.amber400
            override val backgroundHigh = LemonadePrimitiveColors.Solid.Amber.amber200
            override val border = LemonadePrimitiveColors.Solid.Amber.amber400
            override val content = LemonadePrimitiveColors.Solid.Amber.amber400
            override val contentInverse = LemonadePrimitiveColors.Solid.Amber.amber700
            override val onBackground = LemonadePrimitiveColors.Solid.Amber.amber950
            override val onBackgroundHigh = LemonadePrimitiveColors.Solid.Amber.amber900
            override val subtle: ThemedColor =
                object : ThemedColor {
                    override val background = LemonadePrimitiveColors.Alpha.Amber.alpha100
                    override val border = LemonadePrimitiveColors.Alpha.Amber.alpha100
                    override val onBackground = LemonadePrimitiveColors.Solid.Amber.amber400
                }
        }

    override val blue: ThemedPrimaryColor =
        object : ThemedPrimaryColor {
            override val background = LemonadePrimitiveColors.Solid.Blue.blue400
            override val backgroundHigh = LemonadePrimitiveColors.Solid.Blue.blue200
            override val border = LemonadePrimitiveColors.Solid.Blue.blue400
            override val content = LemonadePrimitiveColors.Solid.Blue.blue400
            override val contentInverse = LemonadePrimitiveColors.Solid.Blue.blue700
            override val onBackground = LemonadePrimitiveColors.Solid.Blue.blue950
            override val onBackgroundHigh = LemonadePrimitiveColors.Solid.Blue.blue900
            override val subtle: ThemedColor =
                object : ThemedColor {
                    override val background = LemonadePrimitiveColors.Alpha.Blue.alpha100
                    override val border = LemonadePrimitiveColors.Alpha.Blue.alpha100
                    override val onBackground = LemonadePrimitiveColors.Solid.Blue.blue400
                }
        }

    override val cyan: ThemedPrimaryColor =
        object : ThemedPrimaryColor {
            override val background = LemonadePrimitiveColors.Solid.Cyan.cyan400
            override val backgroundHigh = LemonadePrimitiveColors.Solid.Cyan.cyan200
            override val border = LemonadePrimitiveColors.Solid.Cyan.cyan400
            override val content = LemonadePrimitiveColors.Solid.Cyan.cyan400
            override val contentInverse = LemonadePrimitiveColors.Solid.Cyan.cyan700
            override val onBackground = LemonadePrimitiveColors.Solid.Cyan.cyan950
            override val onBackgroundHigh = LemonadePrimitiveColors.Solid.Cyan.cyan900
            override val subtle: ThemedColor =
                object : ThemedColor {
                    override val background = LemonadePrimitiveColors.Alpha.Cyan.alpha100
                    override val border = LemonadePrimitiveColors.Alpha.Cyan.alpha100
                    override val onBackground = LemonadePrimitiveColors.Solid.Cyan.cyan400
                }
        }

    override val fuchsia: ThemedPrimaryColor =
        object : ThemedPrimaryColor {
            override val background = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia400
            override val backgroundHigh = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia200
            override val border = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia400
            override val content = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia400
            override val contentInverse = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia700
            override val onBackground = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia950
            override val onBackgroundHigh = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia900
            override val subtle: ThemedColor =
                object : ThemedColor {
                    override val background = LemonadePrimitiveColors.Alpha.Fuchsia.alpha100
                    override val border = LemonadePrimitiveColors.Alpha.Fuchsia.alpha100
                    override val onBackground = LemonadePrimitiveColors.Solid.Fuchsia.fuchsia400
                }
        }

    override val green: ThemedPrimaryColor =
        object : ThemedPrimaryColor {
            override val background = LemonadePrimitiveColors.Solid.Green.green400
            override val backgroundHigh = LemonadePrimitiveColors.Solid.Green.green200
            override val border = LemonadePrimitiveColors.Solid.Green.green400
            override val content = LemonadePrimitiveColors.Solid.Green.green400
            override val contentInverse = LemonadePrimitiveColors.Solid.Green.green700
            override val onBackground = LemonadePrimitiveColors.Solid.Green.green950
            override val onBackgroundHigh = LemonadePrimitiveColors.Solid.Green.green900
            override val subtle: ThemedColor =
                object : ThemedColor {
                    override val background = LemonadePrimitiveColors.Alpha.Green.alpha100
                    override val border = LemonadePrimitiveColors.Alpha.Green.alpha100
                    override val onBackground = LemonadePrimitiveColors.Solid.Green.green400
                }
        }

    override val greenLime: ThemedPrimaryColor =
        object : ThemedPrimaryColor {
            override val background = LemonadePrimitiveColors.Solid.GreenLime.greenLime400
            override val backgroundHigh = LemonadePrimitiveColors.Solid.GreenLime.greenLime200
            override val border = LemonadePrimitiveColors.Solid.GreenLime.greenLime400
            override val content = LemonadePrimitiveColors.Solid.GreenLime.greenLime400
            override val contentInverse = LemonadePrimitiveColors.Solid.GreenLime.greenLime700
            override val onBackground = LemonadePrimitiveColors.Solid.GreenLime.greenLime950
            override val onBackgroundHigh = LemonadePrimitiveColors.Solid.GreenLime.greenLime900
            override val subtle: ThemedColor =
                object : ThemedColor {
                    override val background = LemonadePrimitiveColors.Alpha.GreenLime.alpha100
                    override val border = LemonadePrimitiveColors.Alpha.GreenLime.alpha100
                    override val onBackground = LemonadePrimitiveColors.Solid.GreenLime.greenLime400
                }
        }

    override val indigo: ThemedPrimaryColor =
        object : ThemedPrimaryColor {
            override val background = LemonadePrimitiveColors.Solid.Indigo.indigo400
            override val backgroundHigh = LemonadePrimitiveColors.Solid.Indigo.indigo200
            override val border = LemonadePrimitiveColors.Solid.Indigo.indigo400
            override val content = LemonadePrimitiveColors.Solid.Indigo.indigo400
            override val contentInverse = LemonadePrimitiveColors.Solid.Indigo.indigo700
            override val onBackground = LemonadePrimitiveColors.Solid.Indigo.indigo950
            override val onBackgroundHigh = LemonadePrimitiveColors.Solid.Indigo.indigo900
            override val subtle: ThemedColor =
                object : ThemedColor {
                    override val background = LemonadePrimitiveColors.Alpha.Indigo.alpha100
                    override val border = LemonadePrimitiveColors.Alpha.Indigo.alpha100
                    override val onBackground = LemonadePrimitiveColors.Solid.Indigo.indigo400
                }
        }

    override val neutral: ThemedPrimaryColor =
        object : ThemedPrimaryColor {
            override val background = LemonadePrimitiveColors.Solid.Neutral.neutral400
            override val backgroundHigh = LemonadePrimitiveColors.Solid.Neutral.neutral200
            override val border = LemonadePrimitiveColors.Solid.Neutral.neutral400
            override val content = LemonadePrimitiveColors.Solid.White.white900
            override val contentInverse = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val onBackground = LemonadePrimitiveColors.Solid.Neutral.neutral950
            override val onBackgroundHigh = LemonadePrimitiveColors.Solid.Neutral.neutral900
            override val subtle: ThemedColor =
                object : ThemedColor {
                    override val background = LemonadePrimitiveColors.Solid.White.white100
                    override val border = LemonadePrimitiveColors.Solid.White.white100
                    override val onBackground = LemonadePrimitiveColors.Solid.White.white900
                }
        }

    override val orange: ThemedPrimaryColor =
        object : ThemedPrimaryColor {
            override val background = LemonadePrimitiveColors.Solid.Orange.orange400
            override val backgroundHigh = LemonadePrimitiveColors.Solid.Orange.orange200
            override val border = LemonadePrimitiveColors.Solid.Orange.orange400
            override val content = LemonadePrimitiveColors.Solid.Orange.orange400
            override val contentInverse = LemonadePrimitiveColors.Solid.Orange.orange700
            override val onBackground = LemonadePrimitiveColors.Solid.Orange.orange950
            override val onBackgroundHigh = LemonadePrimitiveColors.Solid.Orange.orange900
            override val subtle: ThemedColor =
                object : ThemedColor {
                    override val background = LemonadePrimitiveColors.Alpha.Orange.alpha100
                    override val border = LemonadePrimitiveColors.Alpha.Orange.alpha100
                    override val onBackground = LemonadePrimitiveColors.Solid.Orange.orange400
                }
        }

    override val pink: ThemedPrimaryColor =
        object : ThemedPrimaryColor {
            override val background = LemonadePrimitiveColors.Solid.Pink.pink400
            override val backgroundHigh = LemonadePrimitiveColors.Solid.Pink.pink200
            override val border = LemonadePrimitiveColors.Solid.Pink.pink400
            override val content = LemonadePrimitiveColors.Solid.Pink.pink400
            override val contentInverse = LemonadePrimitiveColors.Solid.Pink.pink700
            override val onBackground = LemonadePrimitiveColors.Solid.Pink.pink950
            override val onBackgroundHigh = LemonadePrimitiveColors.Solid.Pink.pink900
            override val subtle: ThemedColor =
                object : ThemedColor {
                    override val background = LemonadePrimitiveColors.Alpha.Pink.alpha100
                    override val border = LemonadePrimitiveColors.Alpha.Pink.alpha100
                    override val onBackground = LemonadePrimitiveColors.Solid.Pink.pink400
                }
        }

    override val purple: ThemedPrimaryColor =
        object : ThemedPrimaryColor {
            override val background = LemonadePrimitiveColors.Solid.Purple.purple400
            override val backgroundHigh = LemonadePrimitiveColors.Solid.Purple.purple200
            override val border = LemonadePrimitiveColors.Solid.Purple.purple400
            override val content = LemonadePrimitiveColors.Solid.Purple.purple400
            override val contentInverse = LemonadePrimitiveColors.Solid.Purple.purple700
            override val onBackground = LemonadePrimitiveColors.Solid.Purple.purple950
            override val onBackgroundHigh = LemonadePrimitiveColors.Solid.Purple.purple900
            override val subtle: ThemedColor =
                object : ThemedColor {
                    override val background = LemonadePrimitiveColors.Alpha.Purple.alpha100
                    override val border = LemonadePrimitiveColors.Alpha.Purple.alpha100
                    override val onBackground = LemonadePrimitiveColors.Solid.Purple.purple400
                }
        }

    override val red: ThemedPrimaryColor =
        object : ThemedPrimaryColor {
            override val background = LemonadePrimitiveColors.Solid.Red.red400
            override val backgroundHigh = LemonadePrimitiveColors.Solid.Red.red200
            override val border = LemonadePrimitiveColors.Solid.Red.red400
            override val content = LemonadePrimitiveColors.Solid.Red.red400
            override val contentInverse = LemonadePrimitiveColors.Solid.Red.red700
            override val onBackground = LemonadePrimitiveColors.Solid.Red.red950
            override val onBackgroundHigh = LemonadePrimitiveColors.Solid.Red.red900
            override val subtle: ThemedColor =
                object : ThemedColor {
                    override val background = LemonadePrimitiveColors.Alpha.Red.alpha100
                    override val border = LemonadePrimitiveColors.Alpha.Red.alpha100
                    override val onBackground = LemonadePrimitiveColors.Solid.Red.red400
                }
        }

    override val rose: ThemedPrimaryColor =
        object : ThemedPrimaryColor {
            override val background = LemonadePrimitiveColors.Solid.Rose.rose400
            override val backgroundHigh = LemonadePrimitiveColors.Solid.Rose.rose200
            override val border = LemonadePrimitiveColors.Solid.Rose.rose400
            override val content = LemonadePrimitiveColors.Solid.Rose.rose400
            override val contentInverse = LemonadePrimitiveColors.Solid.Rose.rose700
            override val onBackground = LemonadePrimitiveColors.Solid.Rose.rose950
            override val onBackgroundHigh = LemonadePrimitiveColors.Solid.Rose.rose900
            override val subtle: ThemedColor =
                object : ThemedColor {
                    override val background = LemonadePrimitiveColors.Alpha.Rose.alpha100
                    override val border = LemonadePrimitiveColors.Alpha.Rose.alpha100
                    override val onBackground = LemonadePrimitiveColors.Solid.Rose.rose400
                }
        }

    override val teal: ThemedPrimaryColor =
        object : ThemedPrimaryColor {
            override val background = LemonadePrimitiveColors.Solid.Teal.teal400
            override val backgroundHigh = LemonadePrimitiveColors.Solid.Teal.teal200
            override val border = LemonadePrimitiveColors.Solid.Teal.teal400
            override val content = LemonadePrimitiveColors.Solid.Teal.teal400
            override val contentInverse = LemonadePrimitiveColors.Solid.Teal.teal700
            override val onBackground = LemonadePrimitiveColors.Solid.Teal.teal950
            override val onBackgroundHigh = LemonadePrimitiveColors.Solid.Teal.teal900
            override val subtle: ThemedColor =
                object : ThemedColor {
                    override val background = LemonadePrimitiveColors.Alpha.Teal.alpha100
                    override val border = LemonadePrimitiveColors.Alpha.Teal.alpha100
                    override val onBackground = LemonadePrimitiveColors.Solid.Teal.teal400
                }
        }

    override val violet: ThemedPrimaryColor =
        object : ThemedPrimaryColor {
            override val background = LemonadePrimitiveColors.Solid.Violet.violet400
            override val backgroundHigh = LemonadePrimitiveColors.Solid.Violet.violet200
            override val border = LemonadePrimitiveColors.Solid.Violet.violet400
            override val content = LemonadePrimitiveColors.Solid.Violet.violet400
            override val contentInverse = LemonadePrimitiveColors.Solid.Violet.violet700
            override val onBackground = LemonadePrimitiveColors.Solid.Violet.violet950
            override val onBackgroundHigh = LemonadePrimitiveColors.Solid.Violet.violet900
            override val subtle: ThemedColor =
                object : ThemedColor {
                    override val background = LemonadePrimitiveColors.Alpha.Violet.alpha100
                    override val border = LemonadePrimitiveColors.Alpha.Violet.alpha100
                    override val onBackground = LemonadePrimitiveColors.Solid.Violet.violet400
                }
        }

    override val yellow: ThemedPrimaryColor =
        object : ThemedPrimaryColor {
            override val background = LemonadePrimitiveColors.Solid.Yellow.yellow400
            override val backgroundHigh = LemonadePrimitiveColors.Solid.Yellow.yellow200
            override val border = LemonadePrimitiveColors.Solid.Yellow.yellow400
            override val content = LemonadePrimitiveColors.Solid.Yellow.yellow400
            override val contentInverse = LemonadePrimitiveColors.Solid.Yellow.yellow700
            override val onBackground = LemonadePrimitiveColors.Solid.Yellow.yellow950
            override val onBackgroundHigh = LemonadePrimitiveColors.Solid.Yellow.yellow900
            override val subtle: ThemedColor =
                object : ThemedColor {
                    override val background = LemonadePrimitiveColors.Alpha.Yellow.alpha100
                    override val border = LemonadePrimitiveColors.Alpha.Yellow.alpha100
                    override val onBackground = LemonadePrimitiveColors.Solid.Yellow.yellow400
                }
        }

    override val yellowLime: ThemedPrimaryColor =
        object : ThemedPrimaryColor {
            override val background = LemonadePrimitiveColors.Solid.YellowLime.yellowLime400
            override val backgroundHigh = LemonadePrimitiveColors.Solid.YellowLime.yellowLime500
            override val border = LemonadePrimitiveColors.Solid.YellowLime.yellowLime400
            override val content = LemonadePrimitiveColors.Solid.YellowLime.yellowLime400
            override val contentInverse = LemonadePrimitiveColors.Solid.YellowLime.yellowLime700
            override val onBackground = LemonadePrimitiveColors.Solid.YellowLime.yellowLime950
            override val onBackgroundHigh = LemonadePrimitiveColors.Solid.YellowLime.yellowLime900
            override val subtle: ThemedColor =
                object : ThemedColor {
                    override val background = LemonadePrimitiveColors.Alpha.YellowLime.alpha100
                    override val border = LemonadePrimitiveColors.Alpha.YellowLime.alpha100
                    override val onBackground = LemonadePrimitiveColors.Solid.YellowLime.yellowLime400
                }
        }
}
