package com.teya.lemonade

import com.teya.lemonade.core.LemonadeBrandLogos
import org.jetbrains.compose.resources.DrawableResource

/**
 * Auto-generated extension for LemonadeBrandLogos enum providing drawable resources.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the svg-asset-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * @generated by svg-asset-converter.main.kts
 */
@Suppress("MaxLineLength")
public val LemonadeBrandLogos.drawableResource: DrawableResource
    get() = when (this) {
        LemonadeBrandLogos.Amazon -> LemonadeRes.drawable.gen_amazon
        LemonadeBrandLogos.Amex -> LemonadeRes.drawable.gen_amex
        LemonadeBrandLogos.ApplePay -> LemonadeRes.drawable.gen_apple_pay
        LemonadeBrandLogos.Bancomat -> LemonadeRes.drawable.gen_bancomat
        LemonadeBrandLogos.CartesBancaires -> LemonadeRes.drawable.gen_cartes_bancaires
        LemonadeBrandLogos.Diners -> LemonadeRes.drawable.gen_diners
        LemonadeBrandLogos.DirectDebit -> LemonadeRes.drawable.gen_direct_debit
        LemonadeBrandLogos.Discover -> LemonadeRes.drawable.gen_discover
        LemonadeBrandLogos.Edenred -> LemonadeRes.drawable.gen_edenred
        LemonadeBrandLogos.GenericMealOrHealthIssuer -> LemonadeRes.drawable.gen_generic_meal_or_health_issuer
        LemonadeBrandLogos.Girocard -> LemonadeRes.drawable.gen_girocard
        LemonadeBrandLogos.GooglePay -> LemonadeRes.drawable.gen_google_pay
        LemonadeBrandLogos.Jcb -> LemonadeRes.drawable.gen_jcb
        LemonadeBrandLogos.Maestro -> LemonadeRes.drawable.gen_maestro
        LemonadeBrandLogos.Mastercard -> LemonadeRes.drawable.gen_mastercard
        LemonadeBrandLogos.MbWay -> LemonadeRes.drawable.gen_mb_way
        LemonadeBrandLogos.Multibanco -> LemonadeRes.drawable.gen_multibanco
        LemonadeBrandLogos.NfcLogo -> LemonadeRes.drawable.gen_nfc_logo
        LemonadeBrandLogos.PagoBancomat -> LemonadeRes.drawable.gen_pago_bancomat
        LemonadeBrandLogos.Paypal -> LemonadeRes.drawable.gen_paypal
        LemonadeBrandLogos.Pluxee -> LemonadeRes.drawable.gen_pluxee
        LemonadeBrandLogos.Sepa -> LemonadeRes.drawable.gen_sepa
        LemonadeBrandLogos.Sodexo -> LemonadeRes.drawable.gen_sodexo
        LemonadeBrandLogos.Unionpay -> LemonadeRes.drawable.gen_unionpay
        LemonadeBrandLogos.Visa -> LemonadeRes.drawable.gen_visa
    }

/**
 * Auto-generated extension for LemonadeBrandLogos enum providing dark-theme drawable resources.
 *
 * Entries without a `<name>-dark.svg` in svg/brandLogos/ resolve to their light
 * drawable, which is the correct rendering for assets that read equally well on
 * both surfaces.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the svg-asset-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * @generated by svg-asset-converter.main.kts
 */
@Suppress("MaxLineLength")
public val LemonadeBrandLogos.darkDrawableResource: DrawableResource
    get() = when (this) {
        LemonadeBrandLogos.Amazon -> LemonadeRes.drawable.gen_amazon_dark
        LemonadeBrandLogos.Amex -> LemonadeRes.drawable.gen_amex
        LemonadeBrandLogos.ApplePay -> LemonadeRes.drawable.gen_apple_pay_dark
        LemonadeBrandLogos.Bancomat -> LemonadeRes.drawable.gen_bancomat
        LemonadeBrandLogos.CartesBancaires -> LemonadeRes.drawable.gen_cartes_bancaires
        LemonadeBrandLogos.Diners -> LemonadeRes.drawable.gen_diners
        LemonadeBrandLogos.DirectDebit -> LemonadeRes.drawable.gen_direct_debit_dark
        LemonadeBrandLogos.Discover -> LemonadeRes.drawable.gen_discover_dark
        LemonadeBrandLogos.Edenred -> LemonadeRes.drawable.gen_edenred
        LemonadeBrandLogos.GenericMealOrHealthIssuer -> LemonadeRes.drawable.gen_generic_meal_or_health_issuer
        LemonadeBrandLogos.Girocard -> LemonadeRes.drawable.gen_girocard_dark
        LemonadeBrandLogos.GooglePay -> LemonadeRes.drawable.gen_google_pay_dark
        LemonadeBrandLogos.Jcb -> LemonadeRes.drawable.gen_jcb_dark
        LemonadeBrandLogos.Maestro -> LemonadeRes.drawable.gen_maestro
        LemonadeBrandLogos.Mastercard -> LemonadeRes.drawable.gen_mastercard
        LemonadeBrandLogos.MbWay -> LemonadeRes.drawable.gen_mb_way_dark
        LemonadeBrandLogos.Multibanco -> LemonadeRes.drawable.gen_multibanco_dark
        LemonadeBrandLogos.NfcLogo -> LemonadeRes.drawable.gen_nfc_logo_dark
        LemonadeBrandLogos.PagoBancomat -> LemonadeRes.drawable.gen_pago_bancomat
        LemonadeBrandLogos.Paypal -> LemonadeRes.drawable.gen_paypal_dark
        LemonadeBrandLogos.Pluxee -> LemonadeRes.drawable.gen_pluxee_dark
        LemonadeBrandLogos.Sepa -> LemonadeRes.drawable.gen_sepa_dark
        LemonadeBrandLogos.Sodexo -> LemonadeRes.drawable.gen_sodexo
        LemonadeBrandLogos.Unionpay -> LemonadeRes.drawable.gen_unionpay
        LemonadeBrandLogos.Visa -> LemonadeRes.drawable.gen_visa_dark
    }
