package com.teya.lemonade

import androidx.compose.ui.graphics.Color

/**
 * Themed color tokens from Lemonade DS - Foundations.
 *
 * A generic, theme-aware hue palette sitting between the primitive ramps and the
 * semantic tokens in [LemonadeSemanticColors]. Use these when a colour carries
 * application meaning that the design system does not model - chart series,
 * categories, per-role or per-status accents - instead of reaching for
 * [LemonadePrimitiveColors], which is not theme-aware.
 *
 * Each hue carries a saturated palette and a [ThemedPrimaryColor.subtle] one, so a
 * component can hold either as a [ThemedColor] and style itself from it.
 *
 * Prefer a semantic token whenever one fits.
 *
 * Experimental: the shape of this layer is still settling. Opt in with
 * `@OptIn(ExperimentalLemonadeApi::class)` and expect to revisit call sites.
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-themed-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-themed-token-converter.main.kts
 *
 * @generated by scripts/kmp-themed-token-converter.main.kts
 */
@ExperimentalLemonadeApi
public interface LemonadeThemedColors {
    public val amber: AmberColors
    public val blue: BlueColors
    public val cyan: CyanColors
    public val fuchsia: FuchsiaColors
    public val green: GreenColors
    public val greenLime: GreenLimeColors
    public val indigo: IndigoColors
    public val neutral: NeutralColors
    public val orange: OrangeColors
    public val pink: PinkColors
    public val purple: PurpleColors
    public val red: RedColors
    public val rose: RoseColors
    public val teal: TealColors
    public val violet: VioletColors
    public val yellow: YellowColors
    public val yellowLime: YellowLimeColors

    public interface AmberColors : ThemedPrimaryColor

    public interface BlueColors : ThemedPrimaryColor

    public interface CyanColors : ThemedPrimaryColor

    public interface FuchsiaColors : ThemedPrimaryColor

    public interface GreenColors : ThemedPrimaryColor

    public interface GreenLimeColors : ThemedPrimaryColor

    public interface IndigoColors : ThemedPrimaryColor

    public interface NeutralColors : ThemedPrimaryColor

    public interface OrangeColors : ThemedPrimaryColor

    public interface PinkColors : ThemedPrimaryColor

    public interface PurpleColors : ThemedPrimaryColor

    public interface RedColors : ThemedPrimaryColor

    public interface RoseColors : ThemedPrimaryColor

    public interface TealColors : ThemedPrimaryColor

    public interface VioletColors : ThemedPrimaryColor

    public interface YellowColors : ThemedPrimaryColor

    public interface YellowLimeColors : ThemedPrimaryColor
}

/**
 * The slots every themed palette provides, saturated or subtle alike, so one can be
 * passed around as a value - a chart series, a per-role accent, a category.
 *
 * ```
 * val style: ThemedColor = if (subtle) themed.blue.subtle else themed.blue
 * Box(Modifier.background(style.background).border(1.dp, style.border))
 * ```
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-themed-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-themed-token-converter.main.kts
 *
 * @generated by scripts/kmp-themed-token-converter.main.kts
 */
@ExperimentalLemonadeApi
public interface ThemedColor {
    public val background: Color
    public val border: Color
    public val onBackground: Color
}

/**
 * A hue's saturated palette. Adds the slots that only make sense on the hue itself,
 * plus its [subtle] counterpart.
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-themed-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-themed-token-converter.main.kts
 *
 * @generated by scripts/kmp-themed-token-converter.main.kts
 */
@ExperimentalLemonadeApi
public interface ThemedPrimaryColor : ThemedColor {
    public val backgroundHigh: Color
    public val content: Color
    public val contentInverse: Color
    public val onBackgroundHigh: Color
    public val subtle: ThemedColor
}
