package com.teya.lemonade

import androidx.compose.ui.graphics.Color

/**
 * Themed color tokens from Lemonade DS - Foundations.
 *
 * A generic, theme-aware hue palette sitting between the primitive ramps and the
 * semantic tokens in [LemonadeSemanticColors]. Use these when a colour carries
 * application meaning that the design system does not model - chart series,
 * categories, per-role or per-status accents - instead of reaching for
 * [LemonadePrimitiveColors], which is not theme-aware.
 *
 * Prefer a semantic token whenever one fits.
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-themed-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-themed-token-converter.main.kts
 *
 * @generated by scripts/kmp-themed-token-converter.main.kts
 */
public interface LemonadeThemedColors {
    public val amber: AmberColors
    public val blue: BlueColors
    public val cyan: CyanColors
    public val fuchsia: FuchsiaColors
    public val green: GreenColors
    public val greenLime: GreenLimeColors
    public val indigo: IndigoColors
    public val neutral: NeutralColors
    public val orange: OrangeColors
    public val pink: PinkColors
    public val purple: PurpleColors
    public val red: RedColors
    public val rose: RoseColors
    public val teal: TealColors
    public val violet: VioletColors
    public val yellow: YellowColors
    public val yellowLime: YellowLimeColors

    public interface AmberColors : ThemedColor

    public interface BlueColors : ThemedColor

    public interface CyanColors : ThemedColor

    public interface FuchsiaColors : ThemedColor

    public interface GreenColors : ThemedColor

    public interface GreenLimeColors : ThemedColor

    public interface IndigoColors : ThemedColor

    public interface NeutralColors : ThemedColor

    public interface OrangeColors : ThemedColor

    public interface PinkColors : ThemedColor

    public interface PurpleColors : ThemedColor

    public interface RedColors : ThemedColor

    public interface RoseColors : ThemedColor

    public interface TealColors : ThemedColor

    public interface VioletColors : ThemedColor

    public interface YellowColors : ThemedColor

    public interface YellowLimeColors : ThemedColor
}

/**
 * The slots every themed colour provides, so one can be passed around as a value -
 * a chart series, a per-role accent, a category - without naming a specific one.
 *
 * ```
 * val series = listOf(LemonadeTheme.themed.blue, LemonadeTheme.themed.amber)
 * series.map { it.background }
 * ```
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-themed-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-themed-token-converter.main.kts
 *
 * @generated by scripts/kmp-themed-token-converter.main.kts
 */
public interface ThemedColor {
    public val background: Color
    public val backgroundSubtle: Color
    public val border: Color
    public val borderSubtle: Color
    public val content: Color
    public val contentOnColor: Color
    public val onBackground: Color
}
