package com.teya.lemonade

import androidx.compose.ui.graphics.Color

/**
 * Themed color tokens from Lemonade DS - Foundations.
 *
 * A generic, theme-aware hue palette sitting between the primitive ramps and the
 * semantic tokens in [LemonadeSemanticColors]. Use these when a colour carries
 * application meaning that the design system does not model - chart series,
 * categories, per-role or per-status accents - instead of reaching for
 * [LemonadePrimitiveColors], which is not theme-aware.
 *
 * Prefer a semantic token whenever one fits.
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-themed-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-themed-token-converter.main.kts
 *
 * @generated by scripts/kmp-themed-token-converter.main.kts
 */
public interface LemonadeThemedColors {
    public val background: BackgroundColors
    public val border: BorderColors
    public val content: ContentColors

    public interface BackgroundColors {
        public val bgAmber: Color
        public val bgAmberSubtle: Color
        public val bgBlue: Color
        public val bgBlueSubtle: Color
        public val bgCyan: Color
        public val bgCyanSubtle: Color
        public val bgFuchsia: Color
        public val bgFuchsiaSubtle: Color
        public val bgGreen: Color
        public val bgGreenLime: Color
        public val bgGreenLimeSubtle: Color
        public val bgGreenSubtle: Color
        public val bgIndigo: Color
        public val bgIndigoSubtle: Color
        public val bgOrange: Color
        public val bgOrangeSubtle: Color
        public val bgPink: Color
        public val bgPinkSubtle: Color
        public val bgPurple: Color
        public val bgPurpleSubtle: Color
        public val bgRed: Color
        public val bgRedSubtle: Color
        public val bgRose: Color
        public val bgRoseSubtle: Color
        public val bgTeal: Color
        public val bgTealSubtle: Color
        public val bgViolet: Color
        public val bgVioletSubtle: Color
        public val bgYellow: Color
        public val bgYellowLime: Color
        public val bgYellowLimeSubtle: Color
        public val bgYellowSubtle: Color
    }

    public interface BorderColors {
        public val borderAmber: Color
        public val borderAmberSubtle: Color
        public val borderBlue: Color
        public val borderBlueSubtle: Color
        public val borderCyan: Color
        public val borderCyanSubtle: Color
        public val borderFuchsia: Color
        public val borderFuchsiaSubtle: Color
        public val borderGreen: Color
        public val borderGreenLime: Color
        public val borderGreenLimeSubtle: Color
        public val borderGreenSubtle: Color
        public val borderIndigo: Color
        public val borderIndigoSubtle: Color
        public val borderOrange: Color
        public val borderOrangeSubtle: Color
        public val borderPink: Color
        public val borderPinkSubtle: Color
        public val borderPurple: Color
        public val borderPurpleSubtle: Color
        public val borderRed: Color
        public val borderRedSubtle: Color
        public val borderRose: Color
        public val borderRoseSubtle: Color
        public val borderTeal: Color
        public val borderTealSubtle: Color
        public val borderViolet: Color
        public val borderVioletSubtle: Color
        public val borderYellow: Color
        public val borderYellowLime: Color
        public val borderYellowLimeSubtle: Color
        public val borderYellowSubtle: Color
    }

    public interface ContentColors {
        public val contentAmber: Color
        public val contentAmberOnColor: Color
        public val contentBlue: Color
        public val contentBlueOnColor: Color
        public val contentCyan: Color
        public val contentCyanOnColor: Color
        public val contentFuchsia: Color
        public val contentFuchsiaOnColor: Color
        public val contentGreen: Color
        public val contentGreenLime: Color
        public val contentGreenLimeOnColor: Color
        public val contentGreenOnColor: Color
        public val contentIndigo: Color
        public val contentIndigoOnColor: Color
        public val contentOnAmber: Color
        public val contentOnBlue: Color
        public val contentOnCyan: Color
        public val contentOnFuchsia: Color
        public val contentOnGreen: Color
        public val contentOnGreenLime: Color
        public val contentOnIndigo: Color
        public val contentOnOrange: Color
        public val contentOnPink: Color
        public val contentOnPurple: Color
        public val contentOnRed: Color
        public val contentOnRose: Color
        public val contentOnTeal: Color
        public val contentOnViolet: Color
        public val contentOnYellow: Color
        public val contentOnYellowLime: Color
        public val contentOrange: Color
        public val contentOrangeOnColor: Color
        public val contentPink: Color
        public val contentPinkOnColor: Color
        public val contentPurple: Color
        public val contentPurpleOnColor: Color
        public val contentRed: Color
        public val contentRedOnColor: Color
        public val contentRose: Color
        public val contentRoseOnColor: Color
        public val contentTeal: Color
        public val contentTealOnColor: Color
        public val contentViolet: Color
        public val contentVioletOnColor: Color
        public val contentYellow: Color
        public val contentYellowLime: Color
        public val contentYellowLimeOnColor: Color
        public val contentYellowOnColor: Color
    }
}
