// DO NOT MODIFY THIS FILE MANUALLY — generated by scripts/generate-asset-templates.mjs
// url=<LEMONADE_ICONS>?node-id=38-5088
// source=kmp/core/src/commonMain/kotlin/com/teya/lemonade/core/LemonadeIcons.kt
// component=LemonadeIcons
import figma from 'figma'

export default {
  example: figma.kotlin`LemonadeIcons.MoneyDollarPlus`,
  imports: ['import com.teya.lemonade.core.LemonadeIcons'],
  id: 'icon-money-dollar-plus',
  metadata: { nestable: true },
}
