import SwiftUI

// MARK: - Color Namespace Extensions

/// Enables shorthand color access like `.content.contentPrimary`
///
/// Colors automatically adapt to light/dark mode via Asset Catalog.
///
/// ## Usage
/// ```swift
/// Text("Hello")
///     .foregroundStyle(.content.contentPrimary)
///     .background(.bg.bgDefault)
/// ```
///
///  Auto-generated content.
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  @generated by scripts/swiftui-color-assets-generator.main.kts

// MARK: - Background Colors Namespace

public struct LemonadeBackgroundColorsShorthand: Sendable {
    public let bgBrand = Color("lemonade-background-brand-bg-brand", bundle: .lemonade)
    public let bgBrandElevated = Color("lemonade-background-brand-bg-brand-elevated", bundle: .lemonade)
    public let bgBrandHigh = Color("lemonade-background-brand-bg-brand-high", bundle: .lemonade)
    public let bgBrandSubtle = Color("lemonade-background-brand-bg-brand-subtle", bundle: .lemonade)
    public let bgAlwaysDark = Color("lemonade-background-fixed-bg-always-dark", bundle: .lemonade)
    public let bgAlwaysDarkHigh = Color("lemonade-background-fixed-bg-always-dark-high", bundle: .lemonade)
    public let bgAlwaysDarkLow = Color("lemonade-background-fixed-bg-always-dark-low", bundle: .lemonade)
    public let bgAlwaysDarkMedium = Color("lemonade-background-fixed-bg-always-dark-medium", bundle: .lemonade)
    public let bgAlwaysLight = Color("lemonade-background-fixed-bg-always-light", bundle: .lemonade)
    public let bgAlwaysLightHigh = Color("lemonade-background-fixed-bg-always-light-high", bundle: .lemonade)
    public let bgAlwaysLightLow = Color("lemonade-background-fixed-bg-always-light-low", bundle: .lemonade)
    public let bgAlwaysLightMedium = Color("lemonade-background-fixed-bg-always-light-medium", bundle: .lemonade)
    public let bgTransparent = Color("lemonade-background-fixed-bg-transparent", bundle: .lemonade)
    public let bgTransparentDark = Color("lemonade-background-fixed-bg-transparent-dark", bundle: .lemonade)
    public let bgTransparentLight = Color("lemonade-background-fixed-bg-transparent-light", bundle: .lemonade)
    public let bgDefaultInverse = Color("lemonade-background-inverse-bg-default-inverse", bundle: .lemonade)
    public let bgElevatedInverse = Color("lemonade-background-inverse-bg-elevated-inverse", bundle: .lemonade)
    public let bgSubtleInverse = Color("lemonade-background-inverse-bg-subtle-inverse", bundle: .lemonade)
    public let bgCaution = Color("lemonade-background-voice-bg-caution", bundle: .lemonade)
    public let bgCautionSubtle = Color("lemonade-background-voice-bg-caution-subtle", bundle: .lemonade)
    public let bgCritical = Color("lemonade-background-voice-bg-critical", bundle: .lemonade)
    public let bgCriticalSubtle = Color("lemonade-background-voice-bg-critical-subtle", bundle: .lemonade)
    public let bgFeatured = Color("lemonade-background-voice-bg-featured", bundle: .lemonade)
    public let bgFeaturedSubtle = Color("lemonade-background-voice-bg-featured-subtle", bundle: .lemonade)
    public let bgInfo = Color("lemonade-background-voice-bg-info", bundle: .lemonade)
    public let bgInfoSubtle = Color("lemonade-background-voice-bg-info-subtle", bundle: .lemonade)
    public let bgNeutral = Color("lemonade-background-voice-bg-neutral", bundle: .lemonade)
    public let bgNeutralSubtle = Color("lemonade-background-voice-bg-neutral-subtle", bundle: .lemonade)
    public let bgPositive = Color("lemonade-background-voice-bg-positive", bundle: .lemonade)
    public let bgPositiveSubtle = Color("lemonade-background-voice-bg-positive-subtle", bundle: .lemonade)
    public let bgDefault = Color("lemonade-background-bg-default", bundle: .lemonade)
    public let bgElevated = Color("lemonade-background-bg-elevated", bundle: .lemonade)
    public let bgElevatedHigh = Color("lemonade-background-bg-elevated-high", bundle: .lemonade)
    public let bgSubtle = Color("lemonade-background-bg-subtle", bundle: .lemonade)
}

private let lemonadeBackgroundColorsShorthand = LemonadeBackgroundColorsShorthand()

// MARK: - Border Colors Namespace

public struct LemonadeBorderColorsShorthand: Sendable {
    public let borderBrand = Color("lemonade-border-brand-border-brand", bundle: .lemonade)
    public let borderOnBrandHigh = Color("lemonade-border-brand-border-on-brand-high", bundle: .lemonade)
    public let borderOnBrandLow = Color("lemonade-border-brand-border-on-brand-low", bundle: .lemonade)
    public let borderOnBrandMedium = Color("lemonade-border-brand-border-on-brand-medium", bundle: .lemonade)
    public let borderAlwaysDark = Color("lemonade-border-fixed-border-always-dark", bundle: .lemonade)
    public let borderAlwaysDarkHigh = Color("lemonade-border-fixed-border-always-dark-high", bundle: .lemonade)
    public let borderAlwaysDarkLow = Color("lemonade-border-fixed-border-always-dark-low", bundle: .lemonade)
    public let borderAlwaysDarkMedium = Color("lemonade-border-fixed-border-always-dark-medium", bundle: .lemonade)
    public let borderAlwaysLight = Color("lemonade-border-fixed-border-always-light", bundle: .lemonade)
    public let borderAlwaysLightHigh = Color("lemonade-border-fixed-border-always-light-high", bundle: .lemonade)
    public let borderAlwaysLightLow = Color("lemonade-border-fixed-border-always-light-low", bundle: .lemonade)
    public let borderAlwaysLightMedium = Color("lemonade-border-fixed-border-always-light-medium", bundle: .lemonade)
    public let borderBrandInverse = Color("lemonade-border-inverse-border-brand-inverse", bundle: .lemonade)
    public let borderNeutralHighInverse = Color("lemonade-border-inverse-border-neutral-high-inverse", bundle: .lemonade)
    public let borderNeutralLowInverse = Color("lemonade-border-inverse-border-neutral-low-inverse", bundle: .lemonade)
    public let borderNeutralMediumInverse = Color("lemonade-border-inverse-border-neutral-medium-inverse", bundle: .lemonade)
    public let borderSelectedInverse = Color("lemonade-border-inverse-border-selected-inverse", bundle: .lemonade)
    public let borderCaution = Color("lemonade-border-voice-border-caution", bundle: .lemonade)
    public let borderCautionSubtle = Color("lemonade-border-voice-border-caution-subtle", bundle: .lemonade)
    public let borderCritical = Color("lemonade-border-voice-border-critical", bundle: .lemonade)
    public let borderCriticalSubtle = Color("lemonade-border-voice-border-critical-subtle", bundle: .lemonade)
    public let borderFeatured = Color("lemonade-border-voice-border-featured", bundle: .lemonade)
    public let borderFeaturedSubtle = Color("lemonade-border-voice-border-featured-subtle", bundle: .lemonade)
    public let borderInfo = Color("lemonade-border-voice-border-info", bundle: .lemonade)
    public let borderInfoSubtle = Color("lemonade-border-voice-border-info-subtle", bundle: .lemonade)
    public let borderPositive = Color("lemonade-border-voice-border-positive", bundle: .lemonade)
    public let borderPositiveSubtle = Color("lemonade-border-voice-border-positive-subtle", bundle: .lemonade)
    public let borderNeutralHigh = Color("lemonade-border-border-neutral-high", bundle: .lemonade)
    public let borderNeutralLow = Color("lemonade-border-border-neutral-low", bundle: .lemonade)
    public let borderNeutralMedium = Color("lemonade-border-border-neutral-medium", bundle: .lemonade)
    public let borderSelected = Color("lemonade-border-border-selected", bundle: .lemonade)
}

private let lemonadeBorderColorsShorthand = LemonadeBorderColorsShorthand()

// MARK: - Content Colors Namespace

public struct LemonadeContentColorsShorthand: Sendable {
    public let contentBrand = Color("lemonade-content-brand-content-brand", bundle: .lemonade)
    public let contentBrandHigh = Color("lemonade-content-brand-content-brand-high", bundle: .lemonade)
    public let contentOnBrandHigh = Color("lemonade-content-brand-content-on-brand-high", bundle: .lemonade)
    public let contentOnBrandLow = Color("lemonade-content-brand-content-on-brand-low", bundle: .lemonade)
    public let contentAlwaysDark = Color("lemonade-content-fixed-content-always-dark", bundle: .lemonade)
    public let contentAlwaysLight = Color("lemonade-content-fixed-content-always-light", bundle: .lemonade)
    public let contentCautionAlwaysOnColor = Color("lemonade-content-fixed-content-caution-always-on-color", bundle: .lemonade)
    public let contentCriticalAlwaysOnColor = Color("lemonade-content-fixed-content-critical-always-on-color", bundle: .lemonade)
    public let contentInfoAlwaysOnColor = Color("lemonade-content-fixed-content-info-always-on-color", bundle: .lemonade)
    public let contentNeutralAlwaysOnColor = Color("lemonade-content-fixed-content-neutral-always-on-color", bundle: .lemonade)
    public let contentPositiveAlwaysOnColor = Color("lemonade-content-fixed-content-positive-always-on-color", bundle: .lemonade)
    public let contentBrandInverse = Color("lemonade-content-inverse-content-brand-inverse", bundle: .lemonade)
    public let contentPrimaryInverse = Color("lemonade-content-inverse-content-primary-inverse", bundle: .lemonade)
    public let contentSecondaryInverse = Color("lemonade-content-inverse-content-secondary-inverse", bundle: .lemonade)
    public let contentTertiaryInverse = Color("lemonade-content-inverse-content-tertiary-inverse", bundle: .lemonade)
    public let contentCautionOnColor = Color("lemonade-content-voice-on color-content-caution-on-color", bundle: .lemonade)
    public let contentCriticalOnColor = Color("lemonade-content-voice-on color-content-critical-on-color", bundle: .lemonade)
    public let contentFeaturedOnColor = Color("lemonade-content-voice-on color-content-featured-on-color", bundle: .lemonade)
    public let contentInfoOnColor = Color("lemonade-content-voice-on color-content-info-on-color", bundle: .lemonade)
    public let contentNeutralOnColor = Color("lemonade-content-voice-on color-content-neutral-on-color", bundle: .lemonade)
    public let contentPositiveOnColor = Color("lemonade-content-voice-on color-content-positive-on-color", bundle: .lemonade)
    public let contentCaution = Color("lemonade-content-voice-content-caution", bundle: .lemonade)
    public let contentCritical = Color("lemonade-content-voice-content-critical", bundle: .lemonade)
    public let contentFeatured = Color("lemonade-content-voice-content-featured", bundle: .lemonade)
    public let contentInfo = Color("lemonade-content-voice-content-info", bundle: .lemonade)
    public let contentNeutral = Color("lemonade-content-voice-content-neutral", bundle: .lemonade)
    public let contentPositive = Color("lemonade-content-voice-content-positive", bundle: .lemonade)
    public let contentPrimary = Color("lemonade-content-content-primary", bundle: .lemonade)
    public let contentSecondary = Color("lemonade-content-content-secondary", bundle: .lemonade)
    public let contentTertiary = Color("lemonade-content-content-tertiary", bundle: .lemonade)
}

private let lemonadeContentColorsShorthand = LemonadeContentColorsShorthand()

// MARK: - Interaction Colors Namespace

public struct LemonadeInteractionColorsShorthand: Sendable {
    public let bgAlwaysDarkHighInteractive = Color("lemonade-interaction-interactive-background-bg-always-dark-high-interactive", bundle: .lemonade)
    public let bgAlwaysDarkLowInteractive = Color("lemonade-interaction-interactive-background-bg-always-dark-low-interactive", bundle: .lemonade)
    public let bgAlwaysDarkMediumInteractive = Color("lemonade-interaction-interactive-background-bg-always-dark-medium-interactive", bundle: .lemonade)
    public let bgAlwaysLightHighInteractive = Color("lemonade-interaction-interactive-background-bg-always-light-high-interactive", bundle: .lemonade)
    public let bgAlwaysLightLowInteractive = Color("lemonade-interaction-interactive-background-bg-always-light-low-interactive", bundle: .lemonade)
    public let bgAlwaysLightMediumInteractive = Color("lemonade-interaction-interactive-background-bg-always-light-medium-interactive", bundle: .lemonade)
    public let bgBrandElevatedInteractive = Color("lemonade-interaction-interactive-background-bg-brand-elevated-interactive", bundle: .lemonade)
    public let bgBrandHighInteractive = Color("lemonade-interaction-interactive-background-bg-brand-high-interactive", bundle: .lemonade)
    public let bgBrandInteractive = Color("lemonade-interaction-interactive-background-bg-brand-interactive", bundle: .lemonade)
    public let bgCautionInteractive = Color("lemonade-interaction-interactive-background-bg-caution-interactive", bundle: .lemonade)
    public let bgCautionSubtleInteractive = Color("lemonade-interaction-interactive-background-bg-caution-subtle-interactive", bundle: .lemonade)
    public let bgCriticalInteractive = Color("lemonade-interaction-interactive-background-bg-critical-interactive", bundle: .lemonade)
    public let bgCriticalSubtleInteractive = Color("lemonade-interaction-interactive-background-bg-critical-subtle-interactive", bundle: .lemonade)
    public let bgDefaultInteractive = Color("lemonade-interaction-interactive-background-bg-default-interactive", bundle: .lemonade)
    public let bgElevatedHighInteractive = Color("lemonade-interaction-interactive-background-bg-elevated-high-interactive", bundle: .lemonade)
    public let bgElevatedInteractive = Color("lemonade-interaction-interactive-background-bg-elevated-interactive", bundle: .lemonade)
    public let bgFeaturedInteractive = Color("lemonade-interaction-interactive-background-bg-featured-interactive", bundle: .lemonade)
    public let bgFeaturedSubtleInteractive = Color("lemonade-interaction-interactive-background-bg-featured-subtle-interactive", bundle: .lemonade)
    public let bgInfoInteractive = Color("lemonade-interaction-interactive-background-bg-info-interactive", bundle: .lemonade)
    public let bgInfoSubtleInteractive = Color("lemonade-interaction-interactive-background-bg-info-subtle-interactive", bundle: .lemonade)
    public let bgNeutralInteractive = Color("lemonade-interaction-interactive-background-bg-neutral-interactive", bundle: .lemonade)
    public let bgNeutralSubtleInteractive = Color("lemonade-interaction-interactive-background-bg-neutral-subtle-interactive", bundle: .lemonade)
    public let bgPositiveInteractive = Color("lemonade-interaction-interactive-background-bg-positive-interactive", bundle: .lemonade)
    public let bgPositiveSubtleInteractive = Color("lemonade-interaction-interactive-background-bg-positive-subtle-interactive", bundle: .lemonade)
    public let bgSubtleInteractive = Color("lemonade-interaction-interactive-background-bg-subtle-interactive", bundle: .lemonade)
    public let bgBrandElevatedPressed = Color("lemonade-interaction-pressed-background-bg-brand-elevated-pressed", bundle: .lemonade)
    public let bgBrandHighPressed = Color("lemonade-interaction-pressed-background-bg-brand-high-pressed", bundle: .lemonade)
    public let bgBrandPressed = Color("lemonade-interaction-pressed-background-bg-brand-pressed", bundle: .lemonade)
    public let bgCautionPressed = Color("lemonade-interaction-pressed-background-bg-caution-pressed", bundle: .lemonade)
    public let bgCautionSubtlePressed = Color("lemonade-interaction-pressed-background-bg-caution-subtle-pressed", bundle: .lemonade)
    public let bgCriticalPressed = Color("lemonade-interaction-pressed-background-bg-critical-pressed", bundle: .lemonade)
    public let bgCriticalSubtlePressed = Color("lemonade-interaction-pressed-background-bg-critical-subtle-pressed", bundle: .lemonade)
    public let bgDefaultPressed = Color("lemonade-interaction-pressed-background-bg-default-pressed", bundle: .lemonade)
    public let bgElevatedPressed = Color("lemonade-interaction-pressed-background-bg-elevated-pressed", bundle: .lemonade)
    public let bgFeaturedPressed = Color("lemonade-interaction-pressed-background-bg-featured-pressed", bundle: .lemonade)
    public let bgFeaturedSubtlePressed = Color("lemonade-interaction-pressed-background-bg-featured-subtle-pressed", bundle: .lemonade)
    public let bgInfoPressed = Color("lemonade-interaction-pressed-background-bg-info-pressed", bundle: .lemonade)
    public let bgInfoSubtlePressed = Color("lemonade-interaction-pressed-background-bg-info-subtle-pressed", bundle: .lemonade)
    public let bgNeutralPressed = Color("lemonade-interaction-pressed-background-bg-neutral-pressed", bundle: .lemonade)
    public let bgNeutralSubtlePressed = Color("lemonade-interaction-pressed-background-bg-neutral-subtle-pressed", bundle: .lemonade)
    public let bgPositivePressed = Color("lemonade-interaction-pressed-background-bg-positive-pressed", bundle: .lemonade)
    public let bgPositiveSubtlePressed = Color("lemonade-interaction-pressed-background-bg-positive-subtle-pressed", bundle: .lemonade)
    public let bgSubtlePressed = Color("lemonade-interaction-pressed-background-bg-subtle-pressed", bundle: .lemonade)
}

private let lemonadeInteractionColorsShorthand = LemonadeInteractionColorsShorthand()

// MARK: - Scoped Colors Namespace

public struct LemonadeScopedColorsShorthand: Sendable {
    public let bgSettlementBusinessDays = Color("lemonade-scoped-settlements-bg-settlement-business-days", bundle: .lemonade)
    public let bgSettlementEveryday = Color("lemonade-scoped-settlements-bg-settlement-everyday", bundle: .lemonade)
    public let bgSettlementInstant = Color("lemonade-scoped-settlements-bg-settlement-instant", bundle: .lemonade)
    public let bgSettlementScheduled = Color("lemonade-scoped-settlements-bg-settlement-scheduled", bundle: .lemonade)
    public let contentOnSettlementBusinessDays = Color("lemonade-scoped-settlements-content-on-settlement-business-days", bundle: .lemonade)
    public let contentOnSettlementEveryday = Color("lemonade-scoped-settlements-content-on-settlement-everyday", bundle: .lemonade)
    public let contentOnSettlementInstant = Color("lemonade-scoped-settlements-content-on-settlement-instant", bundle: .lemonade)
    public let contentOnSettlementScheduled = Color("lemonade-scoped-settlements-content-on-settlement-scheduled", bundle: .lemonade)
}

private let lemonadeScopedColorsShorthand = LemonadeScopedColorsShorthand()

// MARK: - Shadow Colors Namespace

public struct LemonadeShadowColorsShorthand: Sendable {
    public let shadowDefault = Color("lemonade-shadow-shadow-default", bundle: .lemonade)
}

private let lemonadeShadowColorsShorthand = LemonadeShadowColorsShorthand()

// MARK: - ShapeStyle Extensions

public extension ShapeStyle where Self == Color {
    /// Background color tokens
    /// Usage: `.foregroundStyle(.bg.bgDefault)`
    static var bg: LemonadeBackgroundColorsShorthand { lemonadeBackgroundColorsShorthand }

    /// Border color tokens
    /// Usage: `.foregroundStyle(.border.borderNeutralMedium)`
    static var border: LemonadeBorderColorsShorthand { lemonadeBorderColorsShorthand }

    /// Content color tokens
    /// Usage: `.foregroundStyle(.content.contentPrimary)`
    static var content: LemonadeContentColorsShorthand { lemonadeContentColorsShorthand }

    /// Interaction color tokens
    /// Usage: `.foregroundStyle(.interaction.bgAlwaysDarkHighInteractive)`
    static var interaction: LemonadeInteractionColorsShorthand { lemonadeInteractionColorsShorthand }

    /// Scoped color tokens
    /// Usage: `.foregroundStyle(.scoped.bgSettlementBusinessDays)`
    static var scoped: LemonadeScopedColorsShorthand { lemonadeScopedColorsShorthand }

    /// Shadow color tokens
    /// Usage: `.foregroundStyle(.shadow.shadowDefault)`
    static var shadow: LemonadeShadowColorsShorthand { lemonadeShadowColorsShorthand }

}
