@file:Repository("https://repo1.maven.org/maven2/")
@file:DependsOn("org.json:json:20240303")

import org.json.JSONObject
import java.io.File

data class ResourceData<T>(
    val groups: List<String>,
    val groupFullName: String?,
    val name: String,
    val value: T,
)

fun defaultSwiftAutoGenerationMessage(scriptFilePath: String): String {
    return buildString {
        appendLine(" Auto-generated content.")
        appendLine(" ")
        appendLine(" ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️")
        appendLine(" ")
        appendLine(" This file is automatically generated by the $scriptFilePath script.")
        appendLine(" All changes will be overwritten when the script is run again.")
        appendLine(" ")
        appendLine(" To add updated content:")
        appendLine(" 1. Add your file to the tokens/ directory")
        appendLine(" 2. Run: kotlin $scriptFilePath")
        appendLine(" ")
        appendLine(" @generated by $scriptFilePath")
    }
}

fun <T> List<ResourceData<T?>>.filterNull(): List<ResourceData<T>> {
    val nonNullList = mutableListOf<ResourceData<T>>()
    forEach { resource ->
        if (resource.value != null) {
            nonNullList.add(
                ResourceData(
                    groups = resource.groups,
                    groupFullName = resource.groupFullName,
                    name = resource.name,
                    value = resource.value,
                )
            )
        }
    }
    return nonNullList
}

fun <T> readFileResourceFile(
    file: File,
    resourceMap: (JSONObject) -> T,
): List<ResourceData<T>> {
    val json = JSONObject(file.readText())
    require(isDtcgDocument(json)) { "${file.path} is not a Figma native DTCG export" }
    val resources = dtcgResources(json, resourceMap)
    println("Found ${resources.size} variables")
    return resources
}

/** Resources for one mode. A DTCG export splits modes across files, matched on `com.figma.modeName`. */
fun <T> readFileResourceFileByMode(
    files: List<File>,
    modeName: String,
    resourceMap: (JSONObject) -> T,
): List<ResourceData<T>> {
    files.forEach { file ->
        val json = JSONObject(file.readText())
        require(isDtcgDocument(json)) { "${file.path} is not a Figma native DTCG export" }
        if (!dtcgModeName(json).equals(modeName, ignoreCase = true)) return@forEach
        val resources = dtcgResources(json, resourceMap)
        println("Found ${resources.size} variables for mode $modeName")
        return resources
    }
    error("No token file provides mode '$modeName'")
}

fun String.sanitizedGroups(): List<String> {
    val groups = split("/")
    val valueName = groups.subList(0, groups.lastIndex)
    return valueName.map { group ->
        group
            .split("-")
            .joinToString(separator = "") { word ->
                word.replaceFirstChar { char -> char.uppercase() }
            }
    }
}

fun String.sanitizedSwiftValueName(): String {
    val groups = split("/")
    var valueName = groups[groups.lastIndex]
    if (valueName.isValueNumberOnly()) {
        valueName = groups[groups.lastIndex - 1] + groups[groups.lastIndex]
    }
    return valueName
        .split("/")
        .joinToString("") { group ->
            group
                .split("-")
                .joinToString(separator = "") { word ->
                    word.replaceFirstChar { char -> char.uppercase() }
                }
        }
        .replaceFirstChar { char -> char.lowercase() }
}

fun String.sanitizedSwiftClassName(): String {
    val groups = split("/")
    val valueName = if(groups.size > 1){
        groups.subList(0, groups.lastIndex)
    } else {
        groups
    }
    return valueName.joinToString("") { group ->
        group
            .split("-")
            .joinToString(separator = "") { word ->
                word.replaceFirstChar { char -> char.uppercase() }
            }
    }
}

fun String.isValueNumberOnly(): Boolean {
    return all { it.isDigit() }
}

// ---------------------------------------------------------------------------
// Figma native (DTCG) support
//
// org.json's JSONObject is backed by a HashMap, so keys() does NOT return file
// order. Every traversal below therefore sorts explicitly — without it the
// generated output would be non-deterministic.
// ---------------------------------------------------------------------------

private val EXTENSIONS = "\$extensions"
private val TYPE = "\$type"
private val VALUE = "\$value"

/** A plugin export has a top-level `variables` array; a DTCG document does not. */
fun isDtcgDocument(json: JSONObject): Boolean = !json.has("variables")

/** Compares digit runs numerically, so `border-50` sorts before `border-100`. */
fun naturalCompare(left: String, right: String): Int {
    var i = 0
    var j = 0
    while (i < left.length && j < right.length) {
        val leftChar = left[i]
        val rightChar = right[j]
        if (leftChar.isDigit() && rightChar.isDigit()) {
            var leftEnd = i
            while (leftEnd < left.length && left[leftEnd].isDigit()) leftEnd++
            var rightEnd = j
            while (rightEnd < right.length && right[rightEnd].isDigit()) rightEnd++
            val leftNumber = left.substring(i, leftEnd).trimStart('0').ifEmpty { "0" }
            val rightNumber = right.substring(j, rightEnd).trimStart('0').ifEmpty { "0" }
            if (leftNumber.length != rightNumber.length) return leftNumber.length - rightNumber.length
            val comparison = leftNumber.compareTo(rightNumber)
            if (comparison != 0) return comparison
            i = leftEnd
            j = rightEnd
        } else {
            if (leftChar != rightChar) return leftChar.compareTo(rightChar)
            i++
            j++
        }
    }
    return (left.length - i) - (right.length - j)
}

/** Canonical token ordering: segment by segment, numerically aware. */
fun canonicalTokenOrder(left: String, right: String): Int {
    val leftSegments = left.split("/")
    val rightSegments = right.split("/")
    for (index in 0 until minOf(leftSegments.size, rightSegments.size)) {
        val comparison = naturalCompare(leftSegments[index], rightSegments[index])
        if (comparison != 0) return comparison
    }
    return leftSegments.size - rightSegments.size
}

/** Every leaf token in a DTCG document, keyed by its slash-joined group path. */
fun dtcgTokens(root: JSONObject): Map<String, JSONObject> {
    val tokens = linkedMapOf<String, JSONObject>()
    fun walk(node: JSONObject, path: List<String>) {
        node.keys().asSequence().toList().sortedWith(::naturalCompare).forEach { key ->
            if (key.startsWith("\$")) return@forEach
            val child = node.optJSONObject(key) ?: return@forEach
            if (child.has(TYPE)) {
                tokens[(path + key).joinToString("/")] = child
            } else {
                walk(child, path + key)
            }
        }
    }
    walk(root, emptyList())
    return tokens
}

/** `{a.b.c}` -> `a/b/c`, or null when the value is not a DTCG reference. */
private fun dtcgReferenceTarget(node: JSONObject): String? {
    val value = node.opt(VALUE)
    if (value !is String) return null
    if (!value.startsWith("{") || !value.endsWith("}")) return null
    return value.substring(1, value.length - 1).replace('.', '/')
}

private fun dtcgResolvedValue(tokens: Map<String, JSONObject>, name: String, seen: MutableSet<String>): Any {
    val node = tokens[name] ?: error("DTCG reference '$name' does not exist in this document")
    val target = dtcgReferenceTarget(node)
    if (target != null) {
        if (!seen.add(name)) error("DTCG reference cycle involving '$name'")
        return dtcgResolvedValue(tokens, target, seen)
    }
    return node.get(VALUE)
}

/**
 * Builds the object the converters already expect:
 * `{ "resolvedValue": <number|string|{r,g,b,a}>, "alias": .., "aliasName": .. }`.
 */
fun dtcgResolvedValueObject(tokens: Map<String, JSONObject>, name: String): JSONObject {
    val node = tokens.getValue(name)
    val result = JSONObject()

    val declaredType = node.optString(TYPE)
    require(declaredType in setOf("color", "number", "string")) {
        "Unsupported DTCG \$type '$declaredType' on token '$name'"
    }

    when (val resolved = dtcgResolvedValue(tokens, name, mutableSetOf())) {
        is JSONObject -> {
            val components = resolved.getJSONArray("components")
            require(components.length() >= 3) { "Color token '$name' has fewer than 3 components" }
            result.put(
                "resolvedValue",
                JSONObject()
                    .put("r", components.getDouble(0))
                    .put("g", components.getDouble(1))
                    .put("b", components.getDouble(2))
                    .put("a", resolved.optDouble("alpha", 1.0)),
            )
        }
        else -> result.put("resolvedValue", resolved)
    }

    val aliasData = node.optJSONObject(EXTENSIONS)?.optJSONObject("com.figma.aliasData")
    if (aliasData != null) {
        result.put("alias", aliasData.optString("targetVariableId"))
        result.put("aliasName", aliasData.optString("targetVariableName"))
    } else {
        val target = dtcgReferenceTarget(node)
        if (target != null) {
            result.put("aliasName", target)
            val targetId = tokens[target]?.optJSONObject(EXTENSIONS)?.optString("com.figma.variableId")
            if (!targetId.isNullOrBlank()) result.put("alias", targetId)
        }
    }
    return result
}

private fun isHidden(node: JSONObject): Boolean =
    node.optJSONObject(EXTENSIONS)?.optBoolean("com.figma.hiddenFromPublishing") ?: false

fun dtcgModeName(json: JSONObject): String =
    json.optJSONObject(EXTENSIONS)?.optString("com.figma.modeName").orEmpty()

/** The distinct mode names across [files], in file order. */
fun availableModeNames(files: List<File>): List<String> {
    val names = mutableListOf<String>()
    files.forEach { file ->
        val json = JSONObject(file.readText())
        require(isDtcgDocument(json)) { "${file.path} is not a Figma native DTCG export" }
        val mode = dtcgModeName(json)
        if (mode.isNotBlank() && mode !in names) names.add(mode)
    }
    return names
}

/** Resolves a token file under `tokens/`, failing loudly when it is absent. */
/**
 * Fails unless [files] provide every mode in [required].
 *
 * A theme converter writes only the modes it was given and exits 0, so
 * regenerating from a subset — copying Light in but forgetting Dark — silently
 * leaves the other modes' generated files stale at their previous values, with
 * nothing to catch it: the tree stays clean, so the drift job stays green.
 */
fun requireModes(files: List<File>, vararg required: String) {
    val found = availableModeNames(files)
    val missing = required.filter { want -> found.none { it.equals(want, ignoreCase = true) } }
    require(missing.isEmpty()) {
        "theme tokens are missing mode(s) ${missing.joinToString()} — found " +
            "${found.joinToString().ifEmpty { "none" }}. Copy every " +
            "theme-colors.<mode>.tokens.json from the export; regenerating from a " +
            "subset leaves the other themes stale."
    }
}

fun tokenFile(name: String): File =
    File("tokens/$name").takeIf { it.isFile }
        ?: error("tokens/$name does not exist — copy it in from a Figma variable export")

/**
 * All `tokens/` files whose name starts with [prefix], sorted by name.
 *
 * While both export formats coexist, a DTCG file supersedes the legacy plugin
 * file for the same collection: otherwise mode lookup can land on the legacy
 * file first purely by filename order.
 */
fun tokenFiles(prefix: String): List<File> {
    val matches = (File("tokens").listFiles() ?: emptyArray())
        .filter { it.isFile && it.name.startsWith(prefix) && it.name.endsWith(".json") }
        .sortedBy { it.name }
    val dtcg = matches.filter { it.name.endsWith(".tokens.json") }
    return dtcg.ifEmpty { matches }
}

private fun <T> dtcgResources(
    json: JSONObject,
    resourceMap: (JSONObject) -> T,
): List<ResourceData<T>> {
    val tokens = dtcgTokens(json)
    return tokens.keys
        .sortedWith(::canonicalTokenOrder)
        .filterNot { isHidden(tokens.getValue(it)) }
        .map { name ->
            ResourceData(
                groups = name.sanitizedGroups(),
                groupFullName = name.sanitizedSwiftClassName(),
                name = name.sanitizedSwiftValueName(),
                value = resourceMap(dtcgResolvedValueObject(tokens, name)),
            )
        }
}

/**
 * Visits each non-hidden token for [modeName], handing the callback the raw
 * token name (e.g. `Content/Brand/content-accent`) and its resolved value
 * object. Used where the caller needs the unsanitized name.
 */
fun readFileResourceFileByModeRaw(
    files: List<File>,
    modeName: String,
    visit: (String, JSONObject) -> Unit,
) {
    files.forEach { file ->
        val json = JSONObject(file.readText())
        require(isDtcgDocument(json)) { "${file.path} is not a Figma native DTCG export" }
        if (!dtcgModeName(json).equals(modeName, ignoreCase = true)) return@forEach
        val tokens = dtcgTokens(json)
        tokens.keys
            .sortedWith(::canonicalTokenOrder)
            .filterNot { name ->
                tokens.getValue(name).optJSONObject("\$extensions")
                    ?.optBoolean("com.figma.hiddenFromPublishing") ?: false
            }
            .forEach { name ->
                val resolved = dtcgResolvedValueObject(tokens, name).optJSONObject("resolvedValue")
                if (resolved != null) visit(name, resolved)
            }
        return
    }
    error("No token file provides mode '$modeName'")
}
