#!/usr/bin/env kotlin

import java.io.File

/**
 * Concatenates the entrypoints into one pasteable file.
 *
 * fonts.css is deliberately excluded: it points at local .woff2 files that do not
 * exist in a pasted context. The header tells the reader to use Google Fonts instead,
 * which is the one external host Claude artifacts allow.
 *
 * Order matters: tokens.css (custom properties) must precede typography.css, icon.css
 * and the component stylesheets, which consume those properties via var().
 */

/**
 * One header is enough for the bundle, so each part's own banner is dropped. Only a
 * comment at the very start is a banner: a hand-written stylesheet may open with rules
 * and comment a rule further down, and cutting from that comment would silently take
 * every rule above it.
 */
fun withoutLeadingBanner(css: String): String {
    val text = css.trimStart()
    if (!text.startsWith("/*")) return text.trim()
    val close = text.indexOf("*/")
    if (close < 0) return text.trim()
    return text.substring(close + 2).trim()
}

/**
 * Discovered rather than listed, so a new component cannot be left out of the bundle
 * that prototypes paste — its styles would simply be missing, with every check green.
 */
fun componentStylesheets(): List<String> {
    val root = File("web/src/components")
    if (!root.isDirectory) return emptyList()
    return root.walkTopDown()
        .filter { it.isFile && it.extension == "css" }
        .map { it.path }
        .sorted()
        .toList()
}

fun main() {
    val base = listOf("web/styles/tokens.css", "web/styles/typography.css", "web/styles/icon.css")
    base.forEach { require(File(it).isFile) { "$it is missing — run the converters first" } }
    val parts = base + componentStylesheets()

    val bundle = buildString {
        appendLine("/* Lemonade Design System — self-contained stylesheet.")
        appendLine(" * Generated by scripts/web-css-bundle.main.kts — do not edit.")
        appendLine(" *")
        appendLine(" * Paste into a <style> block. For the Figtree typeface, add:")
        appendLine(" *   @import url('https://fonts.googleapis.com/css2?family=Figtree:wght@400;500;600&display=swap');")
        appendLine(" */")
        parts.forEach { path ->
            appendLine()
            appendLine(withoutLeadingBanner(File(path).readText()))
        }
    }
    File("web/styles/lemonade.css").writeText(bundle + "\n")
    println("✓ web/styles/lemonade.css written (${bundle.length / 1024}KB, ${parts.size} parts)")
}

main()
