#!/usr/bin/env kotlin

import java.io.File

/**
 * Writes the two generated stylesheets: components.css, which is every component's classes,
 * and lemonade.css, which is the whole system in one pasteable file.
 *
 * Component stylesheets are discovered rather than listed, so adding a component cannot
 * leave its classes out of either file — a failure that would surface as a component that
 * renders unstyled for a consumer who never loads the JavaScript, with every check green.
 *
 * fonts.css is deliberately excluded from the bundle: it points at local .woff2 files that
 * do not exist in a pasted context. The header names Google Fonts instead, which is the one
 * external host Claude artifacts allow.
 *
 * Order matters: tokens.css declares the custom properties that every other file reads
 * through var().
 */
fun main() {
    val tokens = "web/styles/tokens.css"
    val typography = "web/styles/typography.css"

    val componentCss = File("web/src/components")
        .walkTopDown()
        .filter { it.isFile && it.extension == "css" }
        .map { it.path }
        .sorted()
        .toList()
    require(componentCss.isNotEmpty()) {
        "no component stylesheet found under web/src/components — the glob is wrong, " +
            "and silently writing an empty components.css would unstyle every component"
    }

    (listOf(tokens, typography) + componentCss).forEach {
        require(File(it).isFile) { "$it is missing — run the converters first" }
    }

    /** Each part carries its own banner or explanatory comment; one header per file is enough. */
    fun body(path: String) = File(path).readText().substringAfter("*/").trim()

    val components = buildString {
        appendLine("/* Lemonade Design System — every component's classes.")
        appendLine(" * Generated by scripts/web-css-bundle.main.kts from web/src/components/**.css — do not edit.")
        appendLine(" *")
        appendLine(" * Needs tokens.css for the custom properties these rules read.")
        appendLine(" */")
        componentCss.forEach {
            appendLine()
            appendLine(body(it))
        }
    }
    File("web/styles/components.css").writeText(components + "\n")
    println("✓ web/styles/components.css written (${componentCss.size} components)")

    val bundle = buildString {
        appendLine("/* Lemonade Design System — self-contained stylesheet.")
        appendLine(" * Generated by scripts/web-css-bundle.main.kts — do not edit.")
        appendLine(" *")
        appendLine(" * Paste into a <style> block. For the Figtree typeface, add:")
        appendLine(" *   @import url('https://fonts.googleapis.com/css2?family=Figtree:wght@400;500;600&display=swap');")
        appendLine(" */")
        listOf(tokens, typography).forEach {
            appendLine()
            appendLine(body(it))
        }
        appendLine()
        appendLine(components.substringAfter("*/").trim())
    }
    File("web/styles/lemonade.css").writeText(bundle + "\n")
    println("✓ web/styles/lemonade.css written (${bundle.length / 1024}KB)")
}

main()
