#!/usr/bin/env kotlin

import java.io.File

/**
 * Concatenates the entrypoints into one pasteable file.
 *
 * fonts.css is deliberately excluded: it points at local .woff2 files that do not
 * exist in a pasted context. The header tells the reader to use Google Fonts instead,
 * which is the one external host Claude artifacts allow.
 *
 * Order matters: tokens.css (custom properties) must precede typography.css and
 * icon.css, which consume those properties via var().
 */
fun main() {
    val parts = listOf("web/styles/tokens.css", "web/styles/typography.css", "web/styles/icon.css")
    parts.forEach { require(File(it).isFile) { "$it is missing — run the converters first" } }

    val bundle = buildString {
        appendLine("/* Lemonade Design System — self-contained stylesheet.")
        appendLine(" * Generated by scripts/web-css-bundle.main.kts — do not edit.")
        appendLine(" *")
        appendLine(" * Paste into a <style> block. For the Figtree typeface, add:")
        appendLine(" *   @import url('https://fonts.googleapis.com/css2?family=Figtree:wght@400;500;600&display=swap');")
        appendLine(" */")
        parts.forEach { path ->
            appendLine()
            // Strip each part's own generated banner; one header is enough.
            appendLine(File(path).readText().substringAfter("*/").trim())
        }
    }
    File("web/styles/lemonade.css").writeText(bundle + "\n")
    println("✓ web/styles/lemonade.css written (${bundle.length / 1024}KB)")
}

main()
