// DO NOT MODIFY THIS FILE MANUALLY — generated by scripts/generate-asset-templates.mjs
// url=<LEMONADE_COMPONENTS>?node-id=18731-1103
// source=swiftui/Sources/Lemonade/LemonadeBrandLogos.swift
// component=LemonadeBrandLogo
import figma from 'figma'

export default {
  example: figma.swift`LemonadeBrandLogo.bancomat`,
  id: 'brandLogo-bancomat',
  metadata: { nestable: true },
}
