// DO NOT MODIFY THIS FILE MANUALLY — generated by scripts/generate-asset-templates.mjs
// url=<LEMONADE_COMPONENTS>?node-id=21423-816
// source=swiftui/Sources/Lemonade/LemonadeBrandLogos.swift
// component=LemonadeBrandLogo
import figma from 'figma'

export default {
  example: figma.swift`LemonadeBrandLogo.genericMealOrHealthIssuer`,
  id: 'brandLogo-generic-meal-or-health-issuer-dark',
  metadata: { nestable: true },
}
