// DO NOT MODIFY THIS FILE MANUALLY — generated by scripts/generate-asset-templates.mjs
// url=<LEMONADE_COMPONENTS>?node-id=2210-611
// source=swiftui/Sources/Lemonade/LemonadeBrandLogos.swift
// component=LemonadeBrandLogo
import figma from 'figma'

export default {
  example: figma.swift`LemonadeBrandLogo.mastercard`,
  id: 'brandLogo-mastercard',
  metadata: { nestable: true },
}
