// DO NOT MODIFY THIS FILE MANUALLY — generated by scripts/generate-asset-templates.mjs
// url=<LEMONADE_COMPONENTS>?node-id=20200-101
// source=swiftui/Sources/Lemonade/LemonadeBrandLogos.swift
// component=LemonadeBrandLogo
import figma from 'figma'

export default {
  example: figma.swift`LemonadeBrandLogo.nfcLogo`,
  id: 'brandLogo-nfc-logo',
  metadata: { nestable: true },
}
