// DO NOT MODIFY THIS FILE MANUALLY — generated by scripts/generate-asset-templates.mjs
// url=<LEMONADE_COMPONENTS>?node-id=8122-11399
// source=swiftui/Sources/Lemonade/LemonadeBrandLogos.swift
// component=LemonadeBrandLogo
import figma from 'figma'

export default {
  example: figma.swift`LemonadeBrandLogo.pagoBancomat`,
  id: 'brandLogo-pago-bancomat',
  metadata: { nestable: true },
}
