// DO NOT MODIFY THIS FILE MANUALLY — generated by scripts/generate-asset-templates.mjs
// url=<LEMONADE_FLAGS>?node-id=1493-15589
// source=swiftui/Sources/Lemonade/LemonadeCountryFlags.swift
// component=LemonadeCountryFlag
import figma from 'figma'

export default {
  example: figma.swift`LemonadeCountryFlag.gSSouthGeorgiaAndSouthSandwichIslands`,
  id: 'flag-GS-south-georgia-and-south-sandwich-islands',
  metadata: { nestable: true },
}
