// DO NOT MODIFY THIS FILE MANUALLY — generated by scripts/generate-asset-templates.mjs
// url=<LEMONADE_FLAGS>?node-id=1493-15516
// source=swiftui/Sources/Lemonade/LemonadeCountryFlags.swift
// component=LemonadeCountryFlag
import figma from 'figma'

export default {
  example: figma.swift`LemonadeCountryFlag.pRPuertoRico`,
  id: 'flag-PR-puerto-rico',
  metadata: { nestable: true },
}
