// DO NOT MODIFY THIS FILE MANUALLY — generated by scripts/generate-asset-templates.mjs
// url=<LEMONADE_FLAGS>?node-id=1493-15492
// source=swiftui/Sources/Lemonade/LemonadeCountryFlags.swift
// component=LemonadeCountryFlag
import figma from 'figma'

export default {
  example: figma.swift`LemonadeCountryFlag.tLTimorLeste`,
  id: 'flag-TL-timor-leste',
  metadata: { nestable: true },
}
