/**
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/web-text-style-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/web-text-style-converter.main.kts
 *
 * @generated by scripts/web-text-style-converter.main.kts
 */

export const textStyles = {
  displayXSmall: {
    className: "lmnd-text-display-xsmall",
    fontSize: "font-size-600",
    lineHeight: "line-height-800",
    fontWeight: "semibold",
    letterSpacing: -0.25,
  },
  displaySmall: {
    className: "lmnd-text-display-small",
    fontSize: "font-size-700",
    lineHeight: "line-height-900",
    fontWeight: "semibold",
    letterSpacing: -0.25,
  },
  displayMedium: {
    className: "lmnd-text-display-medium",
    fontSize: "font-size-900",
    lineHeight: "line-height-1100",
    fontWeight: "semibold",
    letterSpacing: -0.25,
  },
  displayLarge: {
    className: "lmnd-text-display-large",
    fontSize: "font-size-1200",
    lineHeight: "line-height-1400",
    fontWeight: "semibold",
    letterSpacing: -0.25,
  },
  displayXLarge: {
    className: "lmnd-text-display-xlarge",
    fontSize: "font-size-1400",
    lineHeight: "line-height-1600",
    fontWeight: "semibold",
    letterSpacing: -0.25,
  },
  display2XLarge: {
    className: "lmnd-text-display-2xlarge",
    fontSize: "font-size-1600",
    lineHeight: "line-height-1800",
    fontWeight: "semibold",
    letterSpacing: -0.25,
  },
  display3XLarge: {
    className: "lmnd-text-display-3xlarge",
    fontSize: "font-size-1800",
    lineHeight: "line-height-2000",
    fontWeight: "semibold",
    letterSpacing: -0.25,
  },
  headingXLarge: {
    className: "lmnd-text-heading-xlarge",
    fontSize: "font-size-1000",
    lineHeight: "line-height-1200",
    fontWeight: "semibold",
  },
  headingLarge: {
    className: "lmnd-text-heading-large",
    fontSize: "font-size-800",
    lineHeight: "line-height-1000",
    fontWeight: "semibold",
  },
  headingMedium: {
    className: "lmnd-text-heading-medium",
    fontSize: "font-size-700",
    lineHeight: "line-height-900",
    fontWeight: "semibold",
  },
  headingSmall: {
    className: "lmnd-text-heading-small",
    fontSize: "font-size-600",
    lineHeight: "line-height-800",
    fontWeight: "semibold",
  },
  headingXSmall: {
    className: "lmnd-text-heading-xsmall",
    fontSize: "font-size-450",
    lineHeight: "line-height-650",
    fontWeight: "semibold",
  },
  headingXXSmall: {
    className: "lmnd-text-heading-xxsmall",
    fontSize: "font-size-400",
    lineHeight: "line-height-600",
    fontWeight: "semibold",
  },
  bodyXLargeRegular: {
    className: "lmnd-text-body-xlarge-regular",
    fontSize: "font-size-500",
    lineHeight: "line-height-700",
    fontWeight: "regular",
  },
  bodyXLargeMedium: {
    className: "lmnd-text-body-xlarge-medium",
    fontSize: "font-size-500",
    lineHeight: "line-height-700",
    fontWeight: "medium",
  },
  bodyXLargeSemiBold: {
    className: "lmnd-text-body-xlarge-semibold",
    fontSize: "font-size-500",
    lineHeight: "line-height-700",
    fontWeight: "semibold",
  },
  bodyLargeRegular: {
    className: "lmnd-text-body-large-regular",
    fontSize: "font-size-450",
    lineHeight: "line-height-700",
    fontWeight: "regular",
  },
  bodyLargeMedium: {
    className: "lmnd-text-body-large-medium",
    fontSize: "font-size-450",
    lineHeight: "line-height-700",
    fontWeight: "medium",
  },
  bodyLargeSemiBold: {
    className: "lmnd-text-body-large-semibold",
    fontSize: "font-size-450",
    lineHeight: "line-height-700",
    fontWeight: "semibold",
  },
  bodyMediumRegular: {
    className: "lmnd-text-body-medium-regular",
    fontSize: "font-size-400",
    lineHeight: "line-height-600",
    fontWeight: "regular",
  },
  bodyMediumMedium: {
    className: "lmnd-text-body-medium-medium",
    fontSize: "font-size-400",
    lineHeight: "line-height-600",
    fontWeight: "medium",
  },
  bodyMediumSemiBold: {
    className: "lmnd-text-body-medium-semibold",
    fontSize: "font-size-400",
    lineHeight: "line-height-600",
    fontWeight: "semibold",
  },
  bodyMediumBold: {
    className: "lmnd-text-body-medium-bold",
    fontSize: "font-size-400",
    lineHeight: "line-height-600",
    fontWeight: "semibold",
  },
  bodySmallRegular: {
    className: "lmnd-text-body-small-regular",
    fontSize: "font-size-350",
    lineHeight: "line-height-500",
    fontWeight: "regular",
  },
  bodySmallMedium: {
    className: "lmnd-text-body-small-medium",
    fontSize: "font-size-350",
    lineHeight: "line-height-500",
    fontWeight: "medium",
  },
  bodySmallSemiBold: {
    className: "lmnd-text-body-small-semibold",
    fontSize: "font-size-350",
    lineHeight: "line-height-500",
    fontWeight: "semibold",
  },
  bodyXSmallRegular: {
    className: "lmnd-text-body-xsmall-regular",
    fontSize: "font-size-300",
    lineHeight: "line-height-400",
    fontWeight: "regular",
  },
  bodyXSmallMedium: {
    className: "lmnd-text-body-xsmall-medium",
    fontSize: "font-size-300",
    lineHeight: "line-height-400",
    fontWeight: "medium",
  },
  bodyXSmallSemiBold: {
    className: "lmnd-text-body-xsmall-semibold",
    fontSize: "font-size-300",
    lineHeight: "line-height-400",
    fontWeight: "semibold",
  },
  bodyXSmallOverline: {
    className: "lmnd-text-body-xsmall-overline",
    fontSize: "font-size-300",
    lineHeight: "line-height-400",
    fontWeight: "semibold",
    letterSpacing: 1.5,
  },
} as const

export type LemonadeTextStyles = typeof textStyles
